PalisadoesFoundation/talawa-admin

CONTRIBUTING.md

If you find any typo in the file ,please fix it  :)

CONTRIBUTING.md file 

---

README.md

documentation bugfix in the readme section of the readme
Fixes #25

Changed the Readme.md

---

.github/workflows/codeql-analysis.yml
.github/workflows/npm-publish.yml

Enhancement created a pipeline 
Fixes #16

Added flows for the node and code quality

---

README.md

Fixed some links that were broken in the readme file @DangaRanga  @palisadoes  please sir review it. Fixes #38

fixed the links in the readme 

---

.github/workflows/codeql-analysis.yml

Fixes #62 
**Summary**
Similar to #67 

disabled CodeQL cron jobs and push actions

---

package.json
src/components/AdminNavbar/AdminNavbar.module.css
src/components/AdminNavbar/AdminNavbar.test.tsx
src/components/AdminNavbar/AdminNavbar.tsx
src/components/Navbar/Navbar.test.tsx
src/components/Navbar/Navbar.tsx
src/screens/OrgAdminHomePage/OrgAdminHomePage.module.css
yarn.lock

1. Fixes main navbar issue of size, responsiveness, and design
2. Fixes sidebar issue
Fixes #88
Yes
**Summary**
Here on, we will start using this navbar and sidebar for all the pages and use the url and names in the sidebar according to the requirement of the specific page.
**Additional details**
GitHub Externship : 19-05_Sin666_tfa_262
@DangaRanga sir, @palisadoes sir, please review and merge

main-navbar sidebar

---

src/screens/LoginPage/LoginPage.module.css

Feature
Fixes  #178 
**Summary**
In the current website , the border bottom was way to longer for Register heading , making it look weird , this PR fixes the styles and aligns it with the Register heading
No
Yes

Feat : Aligned Border Bottom with the Register Heading 

---

package.json
src/App.tsx
src/GraphQl/Mutations/mutations.ts
src/GraphQl/Queries/Queries.ts
src/screens/OrganizationDashboard/OrganizationDashboard.test.tsx
yarn.lock

Uni Testing for organization Dashboard page page
Changes:
1). gql imported from graphql tag
2). Mock data added to query Organusations_list
3). await method added for load to get over and actual content to get rendered (when load===false)
**Issue Number:** #163  
Also continuation of #157 
Yes

Organisation Dashboard Testing Initialised with use of queries and Mock Data

---

.github/workflows/pull-requests.yml
.github/workflows/push.yml

@palisadoes This will fix this 
https://github.com/PalisadoesFoundation/talawa-admin/issues/108#issuecomment-1003540452
push hook also had to be specified that's why that warning was caused.

fixes codeQL warning

---

.github/workflows/README.md
.github/workflows/pull-requests.yml
.github/workflows/push.yml

1). This PR adds GitHub action for checking Test Coverage and uploading it on CodeQL
2). The initial threshold set is `15%`
3). Coverage Checked for both push and pull-requests
4). Added Codecov badge in Readme
bugfix
Fixes #
#205 
https://github.com/Devesh21700Kumar/talawa-admin/runs/4753092126?check_suite_focus=true
(Tested on my forked branch for push)
Yes

Code coverage actions for Pull-requests and Push with veryGoodOpenSource Threshold Checking

---

src/screens/OrganizationPeople/OrganizationPeople.module.css
src/screens/OrganizationPeople/OrganizationPeople.test.tsx
src/screens/OrganizationPeople/OrganizationPeople.tsx

bugFix
Fixes #223
No
* Mobile View
* Tablet/iPad View
No
**Summary**
No
Parent issue #207 
Yes

[UI-responsiveness] Organization People is fixed

---

src/screens/LoginPage/LoginPage.test.tsx

Testing
Fixes #158 
Yes
No
**Summary**
Adds Unit Tests for Login Page
1). Testing whether the Landing page is rendered or not.
2). Testing whether Registration is up to the mark or not.
No
Parent issue #157
Yes

Add tests for Login Page

---

.github/workflows/countline.py
.github/workflows/pull-requests.yml

Allows us to exclude directories with `countlines.py`
Fixes #1196
N/A
N/A
N/A
**Summary**
We need the ability to ignore directories with `countlines.py`
No
N/A
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

Fixes #239

---

src/components/OrgContriCards/OrgContriCards.test.tsx

bugfix
Fixes #242 
Yes
No
No
Parent issue: #241
Yes

[Fixes] Code Coverage: Create tests for OrgContriCards.tsx

---

src/components/AdminNavbar/AdminNavbar.test.tsx
src/components/AdminNavbar/AdminNavbar.tsx

test
Fixes #250 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for AdminNavbar.tsx 

---

src/components/plugins/DummyPlugin/DummyPlugin.test.jsx

[Fixes] Code Coverage: Create tests for DummyPlugin.tsx

---

src/components/plugins/DummyPlugin/DummyPlugin.test.jsx
src/components/plugins/DummyPlugin2/DummyPlugin2.test.jsx

Test
Fixes #247 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for DummyPlugin2.tsx

---

.eslintrc.json
CONTRIBUTING.md
README.md
package.json
setup/about.js
setup/input.js
setup/markdown/About.md
setup/markdown/Install.md
setup/package_installation.js
setup/start_app.js
setup/user_configuration.js
setup/utils/heading.js
setup/utils/input.js
setup/utils/markdown.js
setup_file.js
yarn.lock

feature
Fixes #18 
Not needed as part of this issue
https://user-images.githubusercontent.com/35868598/158973031-a6372e3a-bc3e-42bf-8d10-17c74c383242.mp4
yes
**Summary**
no
The installer Process will be very smooth now. Users will have the option to use there local backend or talawa deployed backend
Yes

Automated installation

---

src/components/ContriStats/ContriStats.test.tsx

[Fixes] Code Coverage: Create tests for ContriStats.tsx

---

src/components/EventListCard/EventListCard.test.tsx
src/components/EventListCard/EventListCard.tsx

Test
Fixes #252 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for EventListCard.tsx

---

src/components/AddOn/core/AddOnRegister/AddOnRegister.test.js
src/components/AddOn/core/AddOnRegister/AddOnRegister.tsx

Test considering code coverage
Fixes #255
Yes
No
**Summary**
Added tests for `src/components/AddOn/core/AddOnRegister/AddOnRegister.tsx`.
No
Yes

[Fixes] Code Coverage: Create tests for AddOnRegister.tsx

---

src/components/MemberRequestCard/MemberRequestCard.test.tsx
src/components/MemberRequestCard/MemberRequestCard.tsx

[Fixes] Code Coverage: Create tests for MemberRequestCard.tsx

---

src/components/EventListCard/EventListCard.test.tsx
src/components/EventListCard/EventListCard.tsx
src/components/OrgPostCard/OrgPostCard.test.tsx
src/components/OrgPostCard/OrgPostCard.tsx

Test
Fixes #269 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for OrgPostCard.tsx

---

src/components/OrgPeopleListCard/OrgPeopleListCard.test.tsx
src/components/OrgPeopleListCard/OrgPeopleListCard.tsx

Test
Fixes #264 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for OrgPeopleListCard.tsx

---

src/screens/OrganizationDashboard/OrganizationDashboard.module.css
src/screens/OrganizationDashboard/OrganizationDashboard.test.tsx
src/screens/OrganizationDashboard/OrganizationDashboard.tsx

Increased coverage of Testing in OrgAdminDashboard File and wrapped buttons in p for their content to be accessible as nodes
Fixes #273 
Yes

Increased coverage of Testing in OrgAdminDashboard File and wrapped buttons in p for their content to be accessible as nodes

---

src/components/OrganizationCard/OrganizationCard.test.tsx
src/components/OrganizationCardStart/OrganizationCardStart.test.tsx

Test
Fixes #268 
Yes
No
NO
Yes

[Fixes] Code Coverage: Create tests for OrganizationCard.tsx

---

src/components/OrganizationCardStart/OrganizationCardStart.test.tsx

Test
Fixes #267 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for OrganizationCardStart.tsx

---

src/components/AddOn/support/components/SidePanel/SidePanel.test.tsx
src/components/AddOn/support/components/SidePanel/SidePanel.tsx

Testing
Fixes # #257 
Yes
Complete 100% Coverage For This File
**Summary**
Fixes #257 
Yes

Tests for SidePanel Component

---

src/components/OrgUpdate/OrgUpdate.test.tsx
src/components/OrgUpdate/OrgUpdate.tsx

[Fixes] Code Coverage: Create tests for OrgUpdate.tsx

---

src/components/UserUpdate/UserUpdate.test.tsx
src/components/UserUpdate/UserUpdate.tsx

Test
Fixes #263 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for UserUpdate.tsx

---

package.json
src/screens/OrgList/OrgList.test.tsx
src/screens/OrgList/OrgList.tsx
yarn.lock

Test
Fixes #274 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for OrgList.tsx

---

src/screens/OrganizationPeople/OrganizationPeople.test.tsx
src/screens/OrganizationPeople/OrganizationPeople.tsx

Test
Fixes #275 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for OrganizationPeople.tsx

---

src/screens/OrganizationEvents/OrganizationEvents.test.tsx
src/screens/OrganizationEvents/OrganizationEvents.tsx
src/screens/OrganizationPeople/OrganizationPeople.test.tsx
src/screens/OrganizationPeople/OrganizationPeople.tsx

Test
Fixes #272 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for OrganizationEvents.tsx

---

package.json

Test
Fixes #246 
Yes
No
**Summary**
`src/components/plugins/index.ts` file contains only the export statements. So I have excluded it from code coverage.
No
Yes

[Fixes] Code Coverage: Create tests for index.ts

---

src/state/reducers/pluginReducer.test.ts

Added tests for pluginReducer
**Issue Number:** #281 
Fixes #281 
Yes
**Summary**
Added test cases to test the pluginReducer from #281 
No
Yes

[Fixes] Code Coverage: Test plugin reducer

---

src/components/AddOn/AddOn.test.tsx
src/components/AddOn/AddOn.tsx

Tests
Fixes #253 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for AddOn.tsx

---

src/state/reducers/routesReducer.test.ts

Added Testcases
**Issue Number:** #279 
Fixes #279 
Yes , I have Added tests for routeReducer in `src/state/reducer`
Yes

[Fixes] Code Coverage : Add test route reducer

---

src/components/AddOn/support/components/Action/Action.test.tsx

Test
Fixes #258 
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for Action.tsx

---

package.json

Test Cases Added 
**Issue Number:** #260 
Fixes #260 
Yes 
**Summary**
Ignore the file
`src/components/AddOn/support/services/Render.helper.ts`
because it was containing just an empty class definition and a export statement :arrow_down: 
```js
class RenderHelper {}
export default RenderHelper;
```
No
Yes

[Fixes] Code Coverage: Testing Render.helper.ts

---

src/components/AddOn/core/AddOnEntry/AddOnEntry.test.tsx
src/components/AddOn/core/AddOnEntry/AddOnEntry.tsx
src/components/AddOn/support/components/MainContent/MainContent.test.tsx
src/components/AddOn/support/components/MainContent/MainContent.tsx

Fixes #259 
100% test coverage for Main Content file
*Does this PR introduce a breaking change?*
No
*Did you add tests for your changes?*
Yes
*Parent Issue*
#241

100% test coverage for Main Content file

---

src/components/OrgAdminListCard/OrgAdminListCard.test.tsx
src/components/OrgAdminListCard/OrgAdminListCard.tsx

[Fixes] Code Coverage: Create tests for OrgAdminListCard.tsx

---

README.md

Fixes https://github.com/PalisadoesFoundation/talawa-admin/issues/335
- **What kind of change does this PR introduce:** Updates README.md
- **Issue Number:** 335
- **Did you add tests for your code?** No
-
- **Does this PR introduce a breaking change?** No
- **Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?** Yes

Error in copying the .env.example fixed

---

src/components/AddOn/core/AddOnStore/AddOnStore.test.jsx
src/components/AddOn/core/AddOnStore/AddOnStore.tsx

Tests
Fixes #256
Yes
No
No
Yes

[Fixes] Code Coverage: Create tests for AddOnStore.tsx

---

src/components/AddOn/support/services/Plugin.helper.test.ts

What kind of change does this PR introduce?**
Testing Added for Plugin.helper.ts #261 
#261 
yes
**Summary**
Added  a test file 
No
Yes

[Code Coverage ]Add Test: Plugin.helper.ts for #261

---

src/components/AddOn/support/services/Plugin.helper.test.ts
src/state/action-creators/index.test.ts

Tests
#283 
Fixes #283 
Yes
**Summary**
Checking proper function calls
No
Yes

[ Code Coverage ] : Tests for src/state/action-creators/index.ts #283

---

.eslintrc.json
package.json
yarn.lock

Check Added
No
**Summary**
We are writing documentation on TSDoc Inline Comments, and I have added checks for TSDoc syntax 
Yes

Eslint Check Added for TSDoc

---

.prettierrc
package.json

* Add Test: Plugin.helper.ts
* Add test:  for promises
* Added Mock Functions
* add: Mock functions 2
* Add Test : for src/state/action-creators/index.ts
* admin/bugfix/prettier
* admin/pkg-updates
* refractor/pacakge.json/Change-to-correct-version
Fixes #
**Summary**

[BugFix] Prettier fix #344  (#346)

---

INSTALLATION.md

Updating docs
Fixes #382
No
-
-
**Summary**
Improves the installation instructions for setting up talawa-admin.
-
-
Yes

updated INSTALLATION.md

---

INSTALLATION.md

Update docs
Fixes #
No
-
-
**Summary**
Small fix to INSTALLATION.md file.
-
-
Yes

small fix to INSTALLATION.md

---

.env.example
INSTALLATION.md
setup/user_configuration.js
setup/utils.js
src/components/AddOn/core/AddOnEntry/AddOnEntry.test.tsx
src/components/AddOn/core/AddOnRegister/AddOnRegister.test.tsx
src/components/AddOn/core/AddOnStore/AddOnStore.test.tsx
src/components/AddOn/support/components/SidePanel/SidePanel.test.tsx
src/components/ContriStats/ContriStats.test.tsx
src/components/OrgContriCards/OrgContriCards.test.tsx
src/index.tsx
src/screens/LoginPage/LoginPage.tsx

Refractoring
Fixes #390 
Not required
Not required
Not required
**Summary**
Renamed 
`REACT_APP_BACKEND_ENDPOINT` to `REACT_APP_TALAWA_URL`
`REACT_APP_RECAPTCHA_KEY` to `REACT_APP_RECAPTCHA_SITE_KEY`
in codebase
No
-
Yes

Improve Talawa-Admin Installation Documentation

---

INSTALLATION.md

It changes the docs for ease in dev setup
Fixes #393 
NO
yes

Fixes #393 Wrong Command in installation.md

---

src/Constant/constant.spec.ts

This pull request is to include a comprehensive test for the constant.ts  file, which will ensure its proper functionality and performance before it is integrated into the main codebase.
Fixes #399 
yes
**Summary**
Adding test for constant.ts
yes

test : adding test for constant.ts

---

src/Constant/constant.spec.ts
src/Constant/constant.ts
src/components/AddOn/core/AddOnEntry/AddOnEntry.test.tsx
src/components/AddOn/core/AddOnRegister/AddOnRegister.test.tsx
src/components/AddOn/core/AddOnStore/AddOnStore.test.tsx
src/components/AddOn/support/components/SidePanel/SidePanel.test.tsx
src/components/ContriStats/ContriStats.test.tsx
src/components/OrgContriCards/OrgContriCards.test.tsx
src/index.tsx
src/screens/LoginPage/LoginPage.tsx

*What kind of change does this PR introduce?*
This PR contains code refactoring and tests
*Issue Number:*
Fixes #417 
*Did you add tests for your changes?*
Yes, I've added additional test cases for new constants.
*Snapshots/Videos:*
*If relevant, did you update the documentation?*
Not relevant
*Summary*
- Currently, we are accessing the environment variables in multiple files.
- This makes it difficult to maintain and refactor them
- I've replaced all environment variables with constants
- This will make it easy to update environment variables in future
- Also added test case for new constant `RECAPTCHA_SITE_KEY`
- Further explained in Issue #417 
*Does this PR introduce a breaking change?*
No
*Other information*
Not needed …

Replace Environment Variables with Constants

---

setup/user_configuration.js

Fixes # #411 
yes
**Summary**
Removed herokuapp.com reference from user_configuration.js
no
yes

Fixes: #411 Removed herokuapp.com reference

---

src/GraphQl/Mutations/mutations.ts
src/components/AddOn/support/services/Plugin.helper.test.ts
src/components/Pagination/Pagination.test.tsx

This PR introduces the updates in the tests for two files Pagination.tsx and Plugin.helper.tsx
Fixes #400 
Fixes #401
Yes
Plugin.helper.tsx
Pagination.tsx
Not required.
**Summary**
This PR introduces the updates in the test for the two files mentioned above. This will improve the code coverage for those files.
No
No
Yes

Create test for Pagination.tsx and Plugin.helper.tsx

---

package.json

Added reportWebVitals.ts to jest ignore pattern
#397 
No need for adding tests this is a auto-generated file.
Yes

Added reportWebVitals.ts to jest ignore patterns

---

.github/workflows/pull-requests.yml
package.json

Feature
Fixes #445 
NA
NA
**Summary**
Added a new script to check for type errors, and used the same in GitHub workflow file to test PRs.
NA
Yes

Add typechecking script to GitHub Workflow [Fixes #445]

---

src/GraphQl/Queries/Queries.ts
src/components/AdminNavbar/AdminNavbar.test.tsx
src/components/AdminNavbar/AdminNavbar.tsx

it is a PR to fix the issue of the dashboard not opening.
Fixes #412 
No
https://user-images.githubusercontent.com/67755128/217039917-4a3426a7-fd52-4166-8376-e5d7e2a3e9d4.mp4
[drive link](https://drive.google.com/file/d/1yUNK-dhTWMfgLFnCDGOjamHXNJABdQ3A/view?usp=share_link)
No
Yes

fix:orgDash not opening

---

src/GraphQl/Mutations/mutations.ts
src/screens/LoginPage/LoginPage.test.tsx
src/screens/LoginPage/LoginPage.tsx

bug fix
Fixes https://github.com/PalisadoesFoundation/talawa-api/issues/1049
Yes
**Summary**
All necessary details are provided here ->
https://github.com/PalisadoesFoundation/talawa-api/pull/1056

complementary changes to admin portal to fix the security bug

---

src/GraphQl/Mutations/mutations.ts

The post was not being updated inside the Talawa-Admin. Now, it is working fine.
Fixes #464 
Not Required
Not Required
**Summary**
No
No
Yes

fix: post not being updated [Fixes: #464]

---

src/screens/OrgPost/OrgPost.tsx

Removed two footers from the post tab in the dashboard.
Fixes #461 
not required

fixes: #461 fixed pagination footer in post tab

---

package.json
src/css/bootstrap.min.css
src/state/helpers/Action.test.ts
yarn.lock

Updated a few packages in yarn.lock and package.JSON
Fixes #453 
not required

fixed #453: updated yarn.lock and package.JSON into the updated version

---

public/locales/en.json
src/GraphQl/Queries/Queries.ts
src/screens/OrgPost/OrgPost.test.tsx
src/screens/OrgPost/OrgPost.tsx
src/screens/OrganizationEvents/OrganizationEvents.test.tsx
src/screens/OrganizationEvents/OrganizationEvents.tsx
src/screens/OrganizationPeople/OrganizationPeople.test.tsx
src/screens/OrganizationPeople/OrganizationPeople.tsx

Fixes non-working search filters (Bug Fix)
Fixes #460 
No, to avoid a heavier PR.
Yes, [PR-1071-talawa-admin](https://github.com/PalisadoesFoundation/talawa-api/pull/1071) is expected to be simultaneously merged with this PR to avoid breaking of talawa-admin.
Yes

Fixes non-working search filters

---

src/GraphQl/Mutations/mutations.ts
src/components/OrgPeopleListCard/OrgPeopleListCard.tsx

Related to - 
https://github.com/PalisadoesFoundation/talawa-api/pull/1078
Fixes #490 
**Summary**

added removeMember mutation

---

src/state/reducers/routesReducer.test.ts
src/state/reducers/routesReducer.ts

Removed the Contributions Page from Talawa-Admin Dashboard. This PR doesn't remove that page completely, rather, I removed its access from the Menu Bar, which makes a room for further feature addition using the Plugins.
Fixes #484 
Not Required
Not Required.
**Summary**
Removed the Contributions Page from Talawa-Admin Dashboard. This PR doesn't remove that page completely, rather, I removed its access from the Menu Bar, which makes a room for further feature addition using the Plugins.
No
No …

Remove contributions page from router [Fixes #484]

---

.gitignore
src/GraphQl/Mutations/mutations.ts
src/GraphQl/Queries/Queries.ts
src/screens/OrgList/OrgList.tsx
src/screens/OrganizationPeople/OrganizationPeople.tsx

Bugfix: Updates the relevant Scalar types for the parameters of mutations and queries (if any) to the newly added Graphql-scalars introduced by this [PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1085)
Fixes [#1085 of Talawa API](https://github.com/PalisadoesFoundation/talawa-api/pull/1085)
NA
NA
**Summary**
This PR must be merged with the corresponding PR in the Talawa-API repository to ensure that the implementation of the same doesn't break the client.
YES
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING. …

Change the Scalar Types [Provides relevant client side changes for #1085 in Talawa-API]

---

src/screens/OrgList/OrgList.tsx
yarn.lock

feature
Fixes #513
Not needed
Not required
Not required
**Summary**
When the organization is created successfully, the modal closes automatically
no
PR will close #513 
Yes

modal closed after organization is created successfully

---

src/screens/OrgList/OrgList.tsx

a bugfix
#509 
Fixes #
not needed
not required
**Summary**
Now the most recently added Organization displays at top in the list.
no
the PR closes #509 .
Yes

fixed:most recently added Org displays at the top

---

CONTRIBUTING.md

updated contributing

---

public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
src/components/AddOn/core/AddOnEntry/AddOnEntry.tsx
src/components/AddOn/core/AddOnRegister/AddOnRegister.test.tsx
src/components/AddOn/core/AddOnRegister/AddOnRegister.tsx
src/components/AddOn/core/AddOnStore/AddOnStore.tsx

Bugfix
Fixes #504 
yes
not any
**Summary**
Implemented translation in plugin tab
No

Fixed: #504 implemented translation on the plugin tab

---

src/components/AdminNavbar/AdminNavbar.module.css
src/components/AdminNavbar/AdminNavbar.tsx
src/screens/OrganizationDashboard/OrganizationDashboard.module.css
src/screens/OrganizationDashboard/OrganizationDashboard.tsx

a bugfix
#503 
Fixes #
no
Not required.
**Summary**
The Pr closes #503 
No

Added OrgName to the Navbar

---

src/components/EventListCard/EventListCard.tsx
src/screens/OrganizationEvents/OrganizationEvents.tsx

Bugfix
Fixes part of [#1101](https://github.com/PalisadoesFoundation/talawa-api/issues/1101)
Must be merged with this [PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1103) to ensure functionality
NA
NA
NA
**Summary**
Updated the front-end to send request for `createEvent` mutation with the correct format of arguments for `startDate`, `endDate`, `startTime` and `endTime`. Also added default values for `startTime` and `endTime`. Also fixed the `updateEvent` screen to handle all the edge cases.
The time's are appended with a `Z` to denote the UTC format, as `Time` scalar automatically coerces the Time …

Fix create event mutation [Fixes part of #1101 in Talawa-API]

---

src/screens/OrganizationPeople/OrganizationPeople.test.tsx

100% test coverage for `src/screens/OrganizationPeople/OrganizationPeople.tsx`
Added correct mocks and covered every case. 
Closes : #480 
Fixes #
**Summary**
No

Tests for organizationPeople.tsx

---

public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
src/components/AdminNavbar/AdminNavbar.module.css
src/components/AdminNavbar/AdminNavbar.test.tsx
src/components/AdminNavbar/AdminNavbar.tsx

Fixed image not showing up in the navbar, also fixed translation not working for All Organization button.
Fixes #528 
Yes
Not required
**Summary**
Image not showing up in the navbar is fixed, and its css is revamped.2
Added translation in different languages for All Organization button.
No it does'nt.
Yes

Fixed navbar added tests

---

public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
src/GraphQl/Mutations/mutations.ts
src/components/OrgUpdate/OrgUpdate.test.tsx
src/components/OrgUpdate/OrgUpdate.tsx

It fixes the updateOrg component for it to work.
Fixes #531
Yes
.
.
.
.
Not required
**Summary**
It fixes the updateOrg component for it to work.
No
No
Yes

Fix the updateOrg page, and made it to create mutation request [Fixes #531]

---

src/components/EventCalendar/Calendar.module.css
src/components/EventCalendar/Calendar.tsx
src/components/EventListCard/EventListCard.module.css
src/components/EventListCard/EventListCard.test.tsx
src/components/EventListCard/EventListCard.tsx
src/screens/OrganizationEvents/OrganizationEvents.module.css
src/screens/OrganizationEvents/OrganizationEvents.test.tsx
src/screens/OrganizationEvents/OrganizationEvents.tsx

New Feauture
Fixes #478 
yes
[www_screencapture_com_2023-3-6_16_59.webm](https://user-images.githubusercontent.com/73706697/223098871-c4cc9655-2936-45ec-8840-c6ae20afc087.webm)
not Required
**Summary**
Implemented the calendar for the event tab in the dashboard , with visible events on the respective dates. 
not any
not any
yes

Fixes #478 : Implemeneted calendar to the Event tab

---

.husky/post-merge
INSTALLATION.md

a bugfix
#524 
Fixes #
no
not required
Yes
**Summary**
The PR will improve developer experience and hence closes #524 
No

Added post-merge hook using husky

---

INSTALLATION.md

This PR is aimed at fixing the installation instructions for Yarn.
Fixes #578 
**Summary**
Previously, the instructions only provided steps to install Yarn version 3, which caused confusion and errors for beginners who needed to install Yarn version 1 instead.
With this PR, appropriate installation instructions have been added to guide users on how to install Yarn version 1 correctly. Updating the instructions, may improve the user experience and prevent any errors that may arise from using the wrong version of Yarn.
Yes

Fixed Yarn Installation Instructions [Fixes: #578]

---

src/components/PaginationList/PaginationList.tsx

bugfix
Fixes #602 
not required
**Summary**
The recent organizations are rendering on all select option as well.
No
Yes

fixes#602 :organization sorting for all organization

---

src/components/AdminNavbar/AdminNavbar.test.tsx
src/components/AdminNavbar/AdminNavbar.tsx

Bugfix
Fixes #570 
No. 
No
**Summary**
This change removes the notification icon and it's functionality from navbar. It's test is also removed.
No
Yes

removed redundant notification

---

src/components/SuperDashListCard/SuperDashListCard.test.tsx
src/components/SuperDashListCard/SuperDashListCard.tsx

bugfix
Fixes #540 
No
https://user-images.githubusercontent.com/67755128/223808727-06d58308-cd18-4c1d-ae0e-0ae8906e625b.mp4
**Summary**
On previous version it was taking a long time to get to that route as well it is prone to reset the state of the parent component
No
Yes

Fix:routing issue for orgdash page

---

src/screens/OrgList/OrgList.module.css
src/screens/OrgList/OrgList.tsx

A feature change (Changing the position of the search bar)
Fixes #614 
No
**Before** 
**After**
No I did not.
**Summary**
I changed the position of the search for easier and faster navigation. I wanted to try **Search Organization** but it was on the sidebar which made it somewhat harder to move to the sidebar of my screen and then move back to select the desired organization. I realized it would be easier and faster for the search bar posiition to be changed for faster navigation and it also aids the visual design of the page.
No
**Have you read …

Feature Request: Position of the search bar. 

---

src/components/EventCalendar/Calendar.test.tsx
src/components/EventCalendar/Calendar.tsx
src/screens/OrganizationEvents/OrganizationEvents.test.tsx
src/screens/OrganizationEvents/OrganizationEvents.tsx

bug fix
Fixes #550 
yes
**Summary**
Increase the code coverage for components/EventCalendar/Calendar.tsx 
yes

fixes: #550 added test for the calendar

---

src/components/SuperDashListCard/SuperDashListCard.tsx

In the recent PR https://github.com/PalisadoesFoundation/talawa-admin/pull/580 The window.location.replace(url); was replaced with history.push(url); due to which, all the pages which were relying on window's url are failing to load. This PR merge that parameter.
Fixes #636 
Not Relevant
Not Required
Not Required
No
No
Yes

Update Router Function [Fixes #636]

---

src/screens/OrganizationDashboard/OrganizationDashboard.tsx

feature
Issue Number:
#573 
Fixes:
No ran automated test
wrapping cards with react-router-dom link
UI result:
https://user-images.githubusercontent.com/65510943/224144207-c7dd0d48-1285-4442-b8c7-f3d746ed7457.mp4
Summary
Added a on click functionalities that link cards to the menu from the navbar. Users can click on a card and it'll take them to the appropriate section. Issue detailed on #573 
No
Other information
Utilized targets variable destructured from appRoute:
```
const appRoutes = useSelector((state: RootState) => state.appRoutes);
const { targets, configUrl } = appRoutes;
```
Used map and filter …

fix: Interactve card

---

src/components/AdminDashListCard/AdminDashListCard.module.css
src/components/AdminDashListCard/AdminDashListCard.test.tsx
src/components/AdminDashListCard/AdminDashListCard.tsx
src/screens/OrgList/OrgList.tsx

Its kind of feature where right after the login the super admin can access/manage all the provided organisations where the admin can manage only its own organisation other options will be disabled.
Fixes #493 
Yes 
**Summary**
https://github.com/PalisadoesFoundation/talawa-admin/issues/493
Yes

Implemented manage functionality for admin and super admin after login

---

.github/workflows/pull-requests.yml
src/components/OrgPostCard/OrgPostCard.module.css
src/components/OrgPostCard/OrgPostCard.test.tsx
src/components/OrgPostCard/OrgPostCard.tsx

a feature
#545 
Fixes #545 
[Screencast from 09-03-23 01:13:53 AM IST.webm](https://user-images.githubusercontent.com/107215525/223850810-c8784a5b-e254-4b8a-94d9-152e3fa9cb51.webm)
Not required
**Summary**
The feature closes #545

Added folding feature to posts

---

public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
src/GraphQl/Mutations/mutations.ts
src/components/UserPasswordUpdate/UserPasswordUpdate.module.css
src/components/UserPasswordUpdate/UserPasswordUpdate.test.tsx
src/components/UserPasswordUpdate/UserPasswordUpdate.tsx
src/components/UserUpdate/UserUpdate.test.tsx
src/screens/OrgSettings/OrgSettings.test.tsx
src/screens/OrgSettings/OrgSettings.tsx

This PR updates the User Update Page and Adds Update Password Page
Fixes #530 
Yes
Not Required
No
No
Yes

Fix User Update Details Page and Add Update Password Page [Fixes #530]

---

src/components/UserPasswordUpdate/UserPasswordUpdate.tsx

bugfix
Fixes [#674](https://github.com/PalisadoesFoundation/talawa-admin/issues/674) 
No 
https://user-images.githubusercontent.com/86047367/224566142-c9a54b1c-c1a4-454b-bf11-489485d4a91c.mp4
**Summary**
It solves the issue of validates the input that input cannot be empty and new password and confirm password should match if both conditions not triaged than only call API.
No
Yes

fixed the issue of validate the input before submit #674

---

src/screens/LoginPage/LoginPage.module.css
src/screens/LoginPage/LoginPage.test.tsx
src/screens/LoginPage/LoginPage.tsx

password review feature on the log-in modal page.
Fixes issue
- #612 
No
https://user-images.githubusercontent.com/104039356/224178475-63b82528-b34b-4e28-88ed-417e824e487e.mp4
**Summary**
I created a label tag with text "show" on the right side of the password input field and attached a toggle onclick function to display the password when it is clicked so that users can confirm their password before they log-in.

password review feature

---

src/screens/LoginPage/LoginPage.test.tsx
src/screens/LoginPage/LoginPage.tsx

#**What kind of change does this PR introduce?**
This PR introduces a bug fix.
Fixes #585 
No
**Summary**
Earlier, the password field showed a warning even when it satisfied the criteria which leaves a sense of confusion for the user. Fixing this gives a clear idea to the user.
No
Yes

Fix to the issue #585

---

package.json
src/components/EventCalendar/Calendar.test.tsx

Closes: #550 
Fixes #
YESSSSSSSSSSSSSS
**Summary**

Improve test coverage for calendar.tsx

---

src/components/AddOn/core/AddOnRegister/AddOnRegister.tsx
src/components/EventListCard/EventListCard.tsx
src/components/MemberRequestCard/MemberRequestCard.tsx
src/components/OrgAdminListCard/OrgAdminListCard.tsx
src/components/OrgPeopleListCard/OrgPeopleListCard.tsx
src/components/OrgPostCard/OrgPostCard.tsx
src/components/OrgUpdate/OrgUpdate.tsx
src/components/UserListCard/UserListCard.tsx
src/components/UserPasswordUpdate/UserPasswordUpdate.tsx
src/components/UserUpdate/UserUpdate.tsx
src/screens/MemberDetail/MemberDetail.tsx

bugfix
Fixes [#645](https://github.com/PalisadoesFoundation/talawa-admin/issues/645) 
Not reuired
https://user-images.githubusercontent.com/86047367/224801560-b7181207-9ba5-490f-8ddb-0ff56f25056f.mp4
**Summary**
use of toast in place of window.alert and refreshing page for updating the data in component with 2 seconds timeout for user experience so that user have time to read the toast message.
No
Yes

fixed the issue use of toast in place of window.alert #645

---

src/screens/OrgList/OrgList.tsx

Bugfix
Fixes # #686 
Not Required
Before : 
After : 
Not Required
**Summary**
The created At time data was static in the Organization Card in Organization List Tab, which was irrelevant.
No
Yes

fixed the static time data under Organization card in the Organization List tab

---

public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
src/screens/LoginPage/LoginPage.module.css
src/screens/LoginPage/LoginPage.tsx

Feature
Fixes #609
No
**Summary**
The Login Page had a Register button for users who do not own an account. But this was not indicated. This pull request solves that problem.
Yes

Added prompt to Register on Login Page

---

src/components/EventListCard/EventListCard.tsx
src/screens/OrganizationEvents/OrganizationEvents.tsx

Bugfix
Fixes #658 
No
Before :
https://user-images.githubusercontent.com/72144454/225915642-7ea558a9-f306-4157-8519-21a3dfd8e63c.mp4
After:
https://user-images.githubusercontent.com/72144454/225917745-e9bcd1b9-c473-4a62-9632-634b31b24ba7.mp4
No
**Summary**
No
Yes

fixed event checkboxes to update

---

src/screens/LoginPage/LoginPage.module.css
src/screens/OrgList/OrgList.module.css
src/screens/OrgPost/OrgPost.module.css
src/screens/OrganizationEvents/OrganizationEvents.module.css
src/screens/OrganizationPeople/OrganizationPeople.module.css

This change fixes login, create post and create organization modals responsive issues.
Fixes #601 
Not required. Css style edits.
**Summary**
I have removed the set width for the modals allowing them to be more responsive for the indicated screen sizes.
No
Yes

fix: #601 modal responsive width

---

src/screens/MemberDetail/MemberDetail.test.tsx
src/screens/MemberDetail/MemberDetail.tsx
src/screens/OrganizationPeople/OrganizationPeople.tsx

a bugfix closes #646 
#646
Fixes #
not req.
After the PR:
[Screencast from 14-03-23 06:54:14 PM IST.webm](https://user-images.githubusercontent.com/107215525/225045582-c2f3db4d-1e82-4f20-b8e5-8905d9dc7a1c.webm)
**Summary**
This PR is in reponse to the an alternate issue...The issue i made for was to implement the funcitonality to add a button to add members from users but wasn't able to achive it...I went to API side and tried to find the way to implement so and realised that we should first implement the funcitonality of TAGS which will help us do this in an easier way...So i thought of making some UI changes …

added dynamic title to OrgPeople section

---

src/components/SecuredRoute/SecuredRoute.tsx
src/screens/LoginPage/LoginPage.tsx

Bug fix
#656 
Fixes #
No
**Summary**
used the existing toast notification rather than introducing a new one.

Updated session timeout notification toast with already existing one

---

src/screens/LoginPage/LoginPage.module.css
src/screens/LoginPage/LoginPage.tsx

feature
Fixes #386 
yes
**Summary**
Added toggle password to view and hide password for registration page.
no
not any

Fixes: toggle password for registration 

---

src/screens/OrganizationDashboard/OrganizationDashboard.tsx

Minor change in dashboard, added link of the people page to the admin card in the dashboard
Fixes #726 
N/A
https://user-images.githubusercontent.com/103348863/226164726-bed62a03-04c7-452d-8e15-cb4ff31752f7.mp4
**Summary**
YES

Add link to dashboard admin card

---

src/components/SuperDashListCard/SuperDashListCard.module.css
src/components/SuperDashListCard/SuperDashListCard.tsx

This PR fixes an organization's image view.
Fixes #634 
N/A
**Summary**
The UI looked unaligned on mobile and this PR fixes that.
N/A
N/A
Yes

center organization image on mobile

---

src/screens/LoginPage/LoginPage.module.css

bugfix
Fixes #683 
Not Required
**Summary**
There were multiple scrollbars on the organization list page removed all the unnecessary one 
no
yes

fixed: Removed extra scrollbars

---

src/components/AdminNavbar/AdminNavbar.module.css

a bugfix
Fixes #775 
No
No
**Summary**
I have changed some CSS styles only.
No
See above
Yes

Bug Fix: Drawer menu visibility on organizations dashboard

---

public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
src/screens/LoginPage/LoginPage.module.css
src/screens/LoginPage/LoginPage.test.tsx
src/screens/LoginPage/LoginPage.tsx

bugfix
Fixes [#722](https://github.com/PalisadoesFoundation/talawa-admin/issues/722) 
https://user-images.githubusercontent.com/86047367/227928007-f624fb1f-82de-43a8-be54-f25844379fea.mp4
Not relevant
**Summary**
Added confirm password and password mismatch warning and added confirm password preview option.
No
Yes

fixed the issue of Mismatched passwords validation #722

---

.github/workflows/pull-requests.yml

Bugfix
Fixes #831 
NA
NA
NA
**Summary**
Updated the workflow to run as one job, so that the dependencies are not installed multiple times. 
No
NA
Yes

Update PR Workflow to be more efficient [Fixes #831]

---

.github/workflows/pull-requests.yml

Bugfix
Fixes the error due to merging of #832 
NA
NA
NA
**Summary**
@palisadoes The workflow files are not working, as there was a space in the name of the job. This provides a fix for the same.
No
NA
Yes

URGENT: Fix workflow file

---

src/components/OrgUpdate/OrgUpdate.tsx

Bugifx 
Fixes #818 
Not Required 
NA
Not Relevant
**Summary**
- The Update Organization functionality had a bug
- Due to this, the user could not update organization details
- Without updating the image as well
- Fixed this issue
No
NA
Yes

Fixed Organization Update

---

src/components/OrgUpdate/OrgUpdate.tsx

Reverts PalisadoesFoundation/talawa-admin#843
Failed on push.
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/4622064669/attempts/1
You need to fix your tests.

Revert "Fixed Organization Update"

---

public/locales/en.json
src/components/OrgUpdate/OrgUpdate.tsx

Bugifx 
Fixes #818 
Not Required 
NA
Not Relevant
**Summary**
- The Update Organization functionality had a bug
- Due to this, the user could not update organization details
- Without updating the image as well
- Fixed this issue
No
- I'm resubmitting changes from PR #843 
- The PR caused workflow to initially fail and later succeeded 
- Discussed this [here](https://github.com/PalisadoesFoundation/talawa-admin/issues/818#issuecomment-1498155512)
- After merging this, please wait for the workflow to finish running before merging another PR
- If …

Fixed Organization Update and Translation

---

src/App.test.tsx
src/App.tsx
src/components/AddOn/core/AddOnEntry/AddOnEntry.test.tsx
src/components/AddOn/core/AddOnRegister/AddOnRegister.test.tsx
src/components/AddOn/core/AddOnRegister/AddOnRegister.tsx
src/components/AddOn/core/AddOnStore/AddOnStore.test.tsx
src/components/AdminNavbar/AdminNavbar.test.tsx
src/components/EventListCard/EventListCard.test.tsx
src/components/ListNavbar/ListNavbar.test.tsx
src/components/MemberRequestCard/MemberRequestCard.test.tsx
src/components/OrgAdminListCard/OrgAdminListCard.test.tsx
src/components/OrgPeopleListCard/OrgPeopleListCard.test.tsx
src/components/OrgPostCard/OrgPostCard.test.tsx
src/components/OrgUpdate/OrgUpdate.test.tsx
src/components/UserListCard/UserListCard.test.tsx
src/screens/BlockUser/BlockUser.test.tsx
src/screens/ForgotPassword/ForgotPassword.test.tsx
src/screens/LoginPage/LoginPage.test.tsx
src/screens/MemberDetail/MemberDetail.test.tsx
src/screens/OrgContribution/OrgContribution.test.tsx
src/screens/OrgList/OrgList.test.tsx
src/screens/OrgList/OrgList.tsx
src/screens/OrgSettings/OrgSettings.test.tsx
src/screens/OrganizationDashboard/OrganizationDashboard.test.tsx
src/screens/OrganizationEvents/OrganizationEvents.test.tsx
src/screens/OrganizationPeople/OrganizationPeople.test.tsx
src/screens/Requests/Requests.test.tsx
src/screens/Roles/Roles.test.tsx
src/setupTests.ts

This PR fixes the following things:
- Fail tests on warnings
- Fix existing warnings
Fixes #819 
Yes
NR
Not Relevant
**Summary**
This PR fixes the most important problem of warning being pushed by contributors, which were conflicting with workflows.
No
Yes

Fail tests on warning [Priority Needed]

---

src/components/AdminNavbar/AdminNavbar.tsx
src/components/EventListCard/EventListCard.tsx
src/components/MemberRequestCard/MemberRequestCard.tsx
src/components/OrgAdminListCard/OrgAdminListCard.tsx
src/components/OrgPeopleListCard/OrgPeopleListCard.tsx
src/components/OrgPostCard/OrgPostCard.tsx
src/components/OrgUpdate/OrgUpdate.tsx
src/components/UserListCard/UserListCard.tsx
src/components/UserUpdate/UserUpdate.tsx
src/screens/BlockUser/BlockUser.tsx
src/screens/ForgotPassword/ForgotPassword.tsx
src/screens/LoginPage/LoginPage.tsx
src/screens/MemberDetail/MemberDetail.tsx
src/screens/OrgList/OrgList.tsx
src/screens/OrgPost/OrgPost.tsx
src/screens/OrganizationDashboard/OrganizationDashboard.tsx
src/screens/OrganizationEvents/OrganizationEvents.tsx
src/screens/OrganizationPeople/OrganizationPeople.tsx
src/screens/Requests/Requests.tsx
src/screens/Roles/Roles.tsx
src/utils/errorHandler.test.tsx
src/utils/errorHandler.tsx

Refactoring of Api unavailable
Fixes #850 
Yes 
**Summary**
The same block of code was being used in several screens/components, due to this there were some inconsistencies too in the code which would not enable error messages to be translated. All of this is fixed in this PR, not only the code is refactored, it will be easy to debug and customise in the future.
No

Code duplicacy removed

---

src/screens/LoginPage/LoginPage.test.tsx
src/screens/LoginPage/LoginPage.tsx

Reverts PalisadoesFoundation/talawa-admin#828

Revert "Improved signupform validations"

---

src/screens/OrgList/OrgList.test.tsx
src/screens/OrgList/OrgList.tsx

This PR restores the test for search-bar of the OrgList Page.
Fixes #870 
Yes
Yes

Restored SearchBar Test for OrgList Page

---

src/screens/OrgList/OrgList.test.tsx
src/screens/OrgList/OrgList.tsx

Reverts PalisadoesFoundation/talawa-admin#878
The concerns about the tests not being valid require us to revert this PR.

Revert "Restored SearchBar Test for OrgList Page"

---

src/screens/LoginPage/LoginPage.tsx

Security Bug fix
Fixes #864 
Not required.
Not required
**Summary**
Authorization was getting copied on login, this had to be fixed as it is a bug related to security.
No it does not.
Not applicable.
Yes !

Fixed Authorization header getting copied on login

---

.github/workflows/countline.py

Updated countlines.py to exclude typescript test files

Updated countlines.py to exclude typescript test files

---

src/screens/OrgSettings/OrgSettings.test.tsx

bugfix
Fixes [#396 ](https://github.com/PalisadoesFoundation/talawa-admin/issues/396)
Yes
N/A
Not relevant
No
Yes

fixed Code Coverage: Create tests for OrgSettings.tsx #396

---

src/components/OrgPostCard/OrgPostCard.test.tsx
src/components/OrgPostCard/OrgPostCard.tsx

Reverts PalisadoesFoundation/talawa-admin#906
Reverting. Merging this PR caused this problem to surface.
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/4853038227/jobs/8648763222#step:5:4725

Revert "remove redundancy from orgPostCard"

---

src/components/EventCalendar/EventCalendar.test.tsx

bugfix
Fixes #911 
yes
**Summary**
The calendar test fail every month, there was this one hardcoded line which were counting the number of days that was causing failure.
No
Not Any
yes

Fixed calendar test

---

src/components/EventCalendar/EventCalendar.test.tsx

fix in failing test (#913)

---

src/components/OrgPostCard/OrgPostCard.module.css
src/components/OrgPostCard/OrgPostCard.test.tsx
src/components/OrgPostCard/OrgPostCard.tsx
src/screens/OrgPost/OrgPost.module.css
src/screens/OrgPost/OrgPost.tsx

feature
Fixes #921
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/4aecfe72-7543-4d6d-9ba1-ee0163e22692
not required
**Summary**
Implemeneted grid system like Instagram web to provide with a concise and neat view of all the posts.
Features added in this PR:
-     Improved grid view for the dashboard in the post management.
-     A detailed view for post
-     elimination pagination to introduce infinite scroll.
-     Image and video previewer in the modal
NO
NA …

Improved Grid view for the post newsfeed dashboard 

---

.github/workflows/push.yml
README.md
package.json
talawa-admin-docs/xyz.md

The following are the changes introduced in this PR:
- Creation of Talawa Admin workflow for automation documentation in Markdown via TypeDoc
- Updation of package.json
- Updates in ReadME.md links, using complete paths so that Talawa-docs can recognize paths when files get transferred.
Fixes #959 
**Summary**
The generated documentation would be produced in the "talawa-admin-docs" repository. It would dynamically update itself in response to any changes made.
No
Yes

Admin workflow completed with updated package.json

---

.github/workflows/push.yml

{Copy docs to talawa-docs}
Changed from automated-docs to develop

Copy-docs-to-talawa-docs branch update to develop

---

.github/workflows/push.yml

Removed link from generate documentation

Removed dependance of code copying from generate segment

---

src/screens/PageNotFound/PageNotFound.module.css

- Adjusted the positioning of the logo on the 404 error page to ensure full visibility.
- Implemented CSS modifications to prevent the logo from being covered or cut off.
- Tested the changes by navigating to various undefined endpoints, confirming that the logo is now displayed correctly on the 404    error page.
Fixes #1016 
No
Fixed the 404 page
**Summary**
Previously the 404 error page was experiencing an issue where the logo was partially covered, resulting in incomplete visibility.
This commit addresses the bug by ensuring the proper display of the logo on the 404 error page, enhancing the user experience. …

fix: Ensure Full Visibility of Logo on 404 Error Page

---

src/components/UsersTableItem/UserTableItemMocks.ts

Code Coverage: Create tests for src/components/UsersTableItem/UsersTableItem.tsx

---

src/components/UserPortal/EventCard/EventCard.test.tsx

Test
Fixes #1027 
Yes
**Summary**
Added test for src/components/UserPortal/EventCard/EventCard.tsx

created test for src/components/UserPortal/EventCard/EventCard.tsx

---

src/App.tsx
src/components/UserPortal/OrganizationNavbar/OrganizationNavbar.test.tsx
src/components/UserPortal/OrganizationNavbar/OrganizationNavbar.tsx

A feature request.
Issue Number:
Fixes #1069
No
Summary
Added the talawa-admin MVP changes.
Other information
Have you read the contributing guide?

MVP Talawa Admin : Hiding Chat Feature from Talawa Web App

---

src/App.tsx
src/components/UserPortal/PromotedPost/PromotedPost.test.tsx

Create tests for src/components/UserPortal/PromotedPost/PromotedPost.tsx
Fixes #1085 
**Summary**
The tests for PromotedPost.tsx were added
No
Yes

Added Test for PromotedPost.tsx

---

src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx

Create tests for src/components/Advertisements/core/AdvertisementRegiste/AdvertisementRegister.test.tsx
Fixes #1084 
**Summary**
The tests for AdvertisementRegister.tsx were added
No
Yes

Added Tests for AdvertisementRegister.tsx

---

src/screens/EventDashboard/EventDashboard.tsx

- Bug Fix
- Fixes #1089 
- No
- Before :
[cinnamon-2023-11-24T220358+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/b9f7f045-9424-44c4-80c3-49dc3b92837d)
- After : 
[cinnamon-2023-11-24T220451+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/5b88386c-6def-41ff-b319-5a7f02ab1c48)
- Fixes Event Project Responsiveness
- No

Bug Fix :  Fixes Event Project Responsiveness

---

src/components/UserUpdate/UserUpdate.test.tsx
src/components/UserUpdate/UserUpdate.tsx
src/screens/MemberDetail/MemberDetail.tsx

Bug Fix
Fixes #1080
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/c6868457-ec3e-4357-8f04-007df50f4499
**Summary**
Now there is no error while fetching the organization data after coming back to organization dashboard page from edit profile page.

Fixed the error while loading the origanization data

---

src/components/UserPortal/ChatRoom/ChatRoom.test.tsx
src/components/UserPortal/ChatRoom/ChatRoom.tsx

Added tests for src/components/UserPortal/ChatRoom/ChatRoom.tsx 

---

src/components/EventListCard/EventListCard.test.tsx
src/components/EventListCard/EventListCard.tsx

- Improved test coverage for `src/components/EventListCard/EventListCard.tsx`
Fixes #1137 
Yes
No
**Summary**
- Improved test coverage for src/components/EventListCard/EventListCard.tsx
No
Yes

fix: improved test coverage for src/components/EventListCard/EventListCard.tsx

---

.github/dependabot.yaml

feature
Fixes #1104 
**Summary**

feat: added dependabot

---

.github/workflows/pull-requests.yml
.github/workflows/push.yml

Feature: Cache npm dependencies
Fixes #1160 
NA
NA
**Summary**
Added feature to cache npm dependencies in .github/workflows
No
**Have you read the [contributing guide] (https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

Feat: Cache npm dependencies

---

.github/workflows/pull-requests.yml

Reverts PalisadoesFoundation/talawa-admin#1161
I have to revert this. A line you added is causing these PR tests to fail.
1. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7174182075/job/19536488975?pr=1180
2. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7170940986/job/19524818348?pr=1178
3. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7170548121/job/19523527658?pr=1170
Please resubmit

Revert "Pr workflow"

---

public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.test.tsx
src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.tsx

Bug
Fixes #1156 
No
**Summary**
This PR fixes the issue #1156 
No
Yes

Added toast on delete action

---

.github/workflows/pull-requests.yml

Reverts PalisadoesFoundation/talawa-admin#1188
We have to revert this. It is not being applied to the deltas
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7195213165/job/19597384890?pr=1190

Revert "Updated workflow"

---

public/locales/en.json
src/screens/OrganizationPeople/OrganizationPeople.test.tsx
src/screens/OrganizationPeople/OrganizationPeople.tsx

feature
Fixes #1155 
Berfore:
After changes:
https://github.com/PalisadoesFoundation/talawa-admin/assets/127925465/08cc8e04-efac-4385-8cfa-b83464a42008
**Summary**
No
Yes

Single search modal instead of two search modal

---

src/screens/MemberDetail/MemberDetail.test.tsx

Added Tests.
Fixes #1028
Yes
**Summary**
Achieved 100% tests on MemberDetail.tsx
Yes

Added Tests for MemberDetail.tsx

---

src/components/UsersTableItem/UserTableItem.test.tsx
src/components/UsersTableItem/UsersTableItem.tsx
src/screens/BlockUser/BlockUser.test.tsx
src/screens/BlockUser/BlockUser.tsx
src/screens/OrgList/OrgList.tsx
src/screens/OrgPost/OrgPost.test.tsx
src/screens/OrgPost/OrgPost.tsx
src/screens/OrganizationPeople/OrganizationPeople.tsx
src/screens/Requests/Requests.test.tsx
src/screens/Requests/Requests.tsx
src/screens/Users/Users.tsx
src/utils/debounce.ts

feature
Fixes #1174 
Yes
**Summary**
Implemented search only after the user presses the 'Enter' key across all the search bars on Talawa.
No
Yes

feature: search on enter key press

---

src/components/LeftDrawer/LeftDrawer.module.css
src/components/LeftDrawer/LeftDrawer.tsx
src/components/LeftDrawerOrg/LeftDrawerOrg.module.css
src/components/LeftDrawerOrg/LeftDrawerOrg.tsx
src/components/OrganizationScreen/OrganizationScreen.module.css
src/components/OrganizationScreen/OrganizationScreen.test.tsx
src/components/OrganizationScreen/OrganizationScreen.tsx
src/components/SuperAdminScreen/SuperAdminScreen.module.css
src/components/SuperAdminScreen/SuperAdminScreen.test.tsx
src/components/SuperAdminScreen/SuperAdminScreen.tsx

Change in hamburger icon and handling of left drawer. Changed the UI and placement of the button to make the user experience more intuitive
Fixes #1159 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/100770875/a8e72a84-b7bc-4591-9b64-7290974809b3
NA
**Summary**
Change in hamburger icon and handling of left drawer 
NA
YES

Change in hamburger icon and handling of left drawer 

---

.github/workflows/pull-requests.yml

**Issue Number:** #1117 
Fixes #
**Summary**

Update PR_WORKFLOW for delta errors/warning checks

---

src/components/OrgListCard/OrgListCard.test.tsx

Reverts PalisadoesFoundation/talawa-admin#1141

Revert "achieved test coverage for OrgListCard.tsx"

---

public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
src/GraphQl/Mutations/mutations.ts
src/components/Advertisements/Advertisements.tsx
src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.module.css
src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.test.tsx
src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.tsx
src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.module.css
src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx

Reverts PalisadoesFoundation/talawa-admin#1169
This is causing many other PRs to fail.
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7314165023/job/19927801159?pr=1272

Revert "Enabling editing an advertisement"

---

src/screens/UserPortal/Events/Events.test.tsx
src/screens/UserPortal/Events/Events.tsx

Feature
Fixes #1202 
Yes
NA
**Summary**
Added calendar view of events in user portal of talawa for better user experience.
Yes

Implementing Calendar View in the user portal of talawa

---

public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
src/screens/UserPortal/Home/Home.module.css
src/screens/UserPortal/Home/Home.test.tsx
src/screens/UserPortal/Home/Home.tsx

Feature request
Fixes #1198 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/1994e573-493a-4602-abeb-923686e43f57
Test Covered
**Summary**

Redesigning the post dialog of user portal

---

src/components/UserPortal/UserNavbar/UserNavbar.test.tsx
src/components/UserPortal/UserNavbar/UserNavbar.tsx

Fixes #1307 
Yes
[Screencast from 2023-12-28 22-44-07.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/bece8ba6-c064-4ea0-9764-3e4b035869ce)
**Summary**

Fixed-Issue-#1307 User Dropdown in Navbar Not Redirecting Properly.

---

src/screens/OrgList/OrgList.test.tsx
src/screens/OrgList/OrgList.tsx
src/screens/OrgList/OrgListMocks.ts

Test for src/screens/OrgList/OrgList.tsx

---

src/components/OrgListCard/OrgListCard.module.css

Refactoring
Fixes #1290 
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/99531396/76fb9a1b-b4dc-4996-9baf-6faa92470718
No
**Summary**
This PR changes the width of the manage button on the OrgListCard which was hiding the members and admin
For more info, check #1290 
No
Yes

Refactor/improve UI org list

---

INSTALLATION.md
src/screens/LoginPage/LoginPage.tsx

Bugfix: Fixed reappearing of login screen for brief time after login
Fixes #1328
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/39d68cfb-f7aa-4e92-9eb9-dcbd2f48217d
No
**Summary**
-  reappearing of login screen for brief time after login
- reappearing of login screen for brief time if the user was already logged in
No
Yes

fix: Fixed reappearing of login screen for brief time after login

---

src/screens/LoginPage/LoginPage.tsx

Bugfix.
Fixes #1347
No.
No.
**Summary**
Fixes the inconsistent size of the email icon on the registration page.
No.
Yes.

fix: Sizing of the email icon on register page

---

src/components/LeftDrawer/LeftDrawer.tsx

button and icon both color changed as stated
Fixes #1201 
**Summary**

Logout button  color change as stated

---

INSTALLATION.md
src/components/OrgListCard/OrgListCard.module.css
src/components/OrgListCard/OrgListCard.tsx

Show letter based avatar for organizations based on their initials without any image similar to what we are shown on the dashboard page.
Fixes #1345
Before:
After:
**Summary**
Used dicebear api to fetch profile as it was already used in different parts of the application like dashboard, user profile.

Added letter based avatar in case of blank display picture

---

src/screens/LoginPage/LoginPage.tsx
src/screens/UserPortal/UserLoginPage/UserLoginPage.tsx

- It will add clickable link to `The Palisadoes Foundation` logo to redirect to official website .
Fixes #1304 
- No
[cinnamon-2024-01-05T121946+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/b2fb9e8a-1beb-4adf-a50d-2cf990042d07)
**Summary**

Added The palisadoes foundation link to logo

---

src/screens/LoginPage/LoginPage.module.css
src/screens/LoginPage/LoginPage.test.tsx
src/screens/LoginPage/LoginPage.tsx
src/screens/UserPortal/UserLoginPage/UserLoginPage.module.css

Fixes #1173 
No
**Summary**
Restores password check functionality.
Yes

Restore password check functionality

---

src/components/OrgProfileFieldSettings/OrgProfileFieldSettings.test.tsx

Increased the code coverage to 100% for src/components/OrgProfileFieldSettings/OrgProfileFieldSettings.tsx

---

.github/workflows/pull-requests.yml
.github/workflows/push.yml
.husky/post-merge
CONTRIBUTING.md
INSTALLATION.md
package-lock.json

refactoring
Fixes #1418 
No
Yes
**Summary**
Checked if npm install works and changed the npm install --legacy-peer-deps instances to npm install
No
Yes

Changed npm install --legacy-peer-deps to npm install

---

.github/workflows/pull-requests.yml

Added Base branch check to main

Added Base branch check to main

---

src/screens/OrgList/OrgList.test.tsx
src/screens/OrgList/OrgList.tsx

Fixes the failing test for OrgList.tsx component
Fixes #1462 
Yes

fix failing test for OrgList component

---

src/components/AddOn/core/AddOnStore/AddOnStore.test.tsx
src/components/AddOn/core/AddOnStore/AddOnStore.tsx

Added tests for increasing the code coverage of the file to 100%
Fixes #1038 
N/A
Current code coverage:
N/A
**Summary**
It increases the code coverage to 100% which was initially 38%.
No.
Yes

Increased code coverage for src/components/AddOn/core/AddOnStore/AddOnStore.tsx file

---

__mocks__/@dicebear/collection.ts
__mocks__/@dicebear/core.ts
jest.config.js
package-lock.json
package.json
src/components/Avatar/Avatar.test.tsx
src/components/Avatar/Avatar.tsx
src/components/LeftDrawer/LeftDrawer.tsx
src/components/LeftDrawerEvent/LeftDrawerEvent.tsx
src/components/LeftDrawerOrg/LeftDrawerOrg.tsx
src/components/OrgListCard/OrgListCard.tsx
src/components/UserPortal/ContactCard/ContactCard.tsx
src/components/UsersTableItem/UsersTableItem.tsx
src/screens/MemberDetail/MemberDetail.tsx

Reverts PalisadoesFoundation/talawa-admin#1634

Revert "Revert "feat: Integrated Dicebear Library To Enhance Security""

---

schema.graphql
src/App.test.tsx
src/GraphQl/Mutations/mutations.ts
src/GraphQl/Queries/Queries.ts
src/components/LeftDrawer/LeftDrawer.test.tsx
src/components/LeftDrawer/LeftDrawer.tsx
src/components/LeftDrawerOrg/LeftDrawerOrg.test.tsx
src/components/LeftDrawerOrg/LeftDrawerOrg.tsx
src/screens/LoginPage/LoginPage.tsx
src/screens/OrgList/OrgList.test.tsx
src/screens/OrgList/OrgList.tsx
src/screens/OrgList/OrgListMocks.ts
src/screens/OrgList/OrganizationModal.tsx
src/utils/interfaces.ts

refactoring
Fixes #1445 
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/132701661/fe9681be-bc5c-4b29-9d97-a9e9fdac0da3
No
**Summary**
This PR fixes the usage of usertype in orglist screen and some more modifications to Login.
yes
yes

fixes usage of userType in orglist screen and some modifications in Login

---

src/screens/OrganizationPeople/OrganizationPeople.test.tsx
src/screens/OrganizationPeople/OrganizationPeople.tsx

refactoring
Fixes #1683 
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/132701661/0b73a3ac-521a-46ec-99f8-8567db609b09
No
**Summary**
This PR fixes the usage of userType field in OrganizationPeople screen.
Yes
Yes

Fixes usage of userType in OrganizationPeople screen

---

ISSUE_GUIDELINES.md

Trivial PR

---

public/locales/en.json
src/components/Advertisements/Advertisements.tsx
src/screens/OrgSettings/OrgSettings.tsx
src/screens/OrganizationEvents/OrganizationEvents.test.tsx
src/screens/OrganizationEvents/OrganizationEvents.tsx

feature
Fixes #1737 
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/132701661/286fb6e8-352f-42da-b7d0-40c1a2c368a5
**Summary**
Some minor tweaks related to UI/UX.
No
Yes

Minor tweaks in admin

---

src/assets/css/app.css
src/components/CollapsibleDropdown/CollapsibleDropdown.tsx
src/components/LeftDrawer/LeftDrawer.module.css
src/components/LeftDrawer/LeftDrawer.test.tsx
src/components/LeftDrawer/LeftDrawer.tsx
src/components/LeftDrawerOrg/LeftDrawerOrg.module.css
src/components/LeftDrawerOrg/LeftDrawerOrg.tsx
src/components/OrganizationScreen/OrganizationScreen.module.css
src/components/OrganizationScreen/OrganizationScreen.tsx
src/screens/MemberDetail/MemberDetail.test.tsx
src/screens/MemberDetail/MemberDetail.tsx

Refactoring
Fixes #1612 
Yes
Yes

Redesign LeftDrawer

---

src/screens/LoginPage/LoginPage.tsx

Reverts PalisadoesFoundation/talawa-admin#1797
We get these errors when loading the Admin app

Revert "Fixed Unauthorized User Access to Admin Portal"

---

src/screens/LoginPage/LoginPage.tsx

bugfix
Fixes #1792 
Changed Lines are already covered
https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/1d9f69f8-204b-4159-aa5b-3043ef78fc96
**Summary**
- Added Error toast & prevent user's unauthorized access to Admin Portal
- Revised Admin/SuperAdmin Login Privileges to UserPortal
No
Yes

Fixed Unauthorized Access & Revised Login Privileges

---

package.json

Disables error overlay in development mode
Fixes #1814
**Summary**

Update serve script to disable ESLint dev errors

---

src/GraphQl/Queries/Queries.ts

Fixed the organization People screen.
Fixes #1805 
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/132201033/53a1185d-8a8f-47b6-bbf6-e8171d189c5f

fixed organizationMember query

---

public/locales/en.json
src/components/UserPortal/UserSidebar/UserSidebar.tsx
src/screens/UserPortal/Home/Home.test.tsx
src/screens/UserPortal/Home/Home.tsx

bugfix
Fixes #1829 
Yes 
https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/0cb315c6-4147-4ada-94ff-2be038174b19
**Summary**
- Fixed the way organizationId is passed in Url Params.
- Updated Test case in Home.tsx to handle above change
No
Yes

Fixed Format of params passed via Url in User Portal

---

src/components/RecurrenceOptions/RecurrenceOptions.test.tsx
src/screens/OrganizationPeople/AddMember.tsx
src/screens/OrganizationPeople/OrganizationPeople.test.tsx

bugfix
Fixes #1842 
https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/04014014-de66-4de5-8e9b-bc1cde405a32
**Summary**

Fix add existing user functionality

---

public/index.html
src/components/EventCalendar/EventCalendar.module.css
src/components/EventCalendar/EventCalendar.test.tsx
src/components/EventCalendar/EventCalendar.tsx
src/components/EventCalendar/constants.js
src/components/EventListCard/EventListCard.module.css
src/components/EventListCard/EventListCard.tsx
src/components/HolidayCards/HolidayCard.module.css
src/components/HolidayCards/HolidayCard.tsx
src/screens/OrganizationActionItems/OrganizationActionItems.module.css
src/screens/UserPortal/Events/Events.module.css
src/screens/UserPortal/Events/Events.tsx
src/utils/getOrganizationId.ts

Fixes #1608 #1850 #1851
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/c32a6932-6d0d-4e60-a229-a20a5d0e6a81
**Summary**

New Event Calendars for Admin and User Portals with working functionalities

---

src/GraphQl/Queries/OrganizationQueries.ts
src/components/UserPortal/OrganizationCard/OrganizationCard.test.tsx
src/components/UserPortal/UserSidebar/UserSidebar.test.tsx
src/screens/UserPortal/Organizations/Organizations.test.tsx
src/screens/UserPortal/Organizations/Organizations.tsx

User will able to join the organization.
Fixes #1849 
**Summary**

 Bug Report: User unable to join Organizations error solved

---

src/components/LeftDrawer/LeftDrawer.test.tsx
src/components/LeftDrawer/LeftDrawer.tsx
src/components/LeftDrawerOrg/LeftDrawerOrg.module.css
src/components/LeftDrawerOrg/LeftDrawerOrg.test.tsx
src/components/LeftDrawerOrg/LeftDrawerOrg.tsx
src/components/OrganizationScreen/OrganizationScreen.module.css
src/components/OrganizationScreen/OrganizationScreen.test.tsx
src/components/OrganizationScreen/OrganizationScreen.tsx
src/components/SuperAdminScreen/SuperAdminScreen.test.tsx
src/components/SuperAdminScreen/SuperAdminScreen.tsx

Refactoring of the left Drawer component in tablet  and mobile screens.
Fixes #1897 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/4f9ecbff-758c-46ec-98d4-5e39895d6e77
Also fixes
- Current Situation
https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/67cb7e78-5743-4273-bff7-320d55628ecc
- After the fixes from this PR
https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/bb9e8c82-73bd-400f-9eaa-f4e7ff323738
N/A
**Summary**
- Adjusted the left drawer component to function properly on screens with a width of 820px or less.
- Ensured smooth expansion and …

fix: Fixed inconsistent left drawer expansion/collapse behavior

---

src/screens/UserPortal/Events/Events.test.tsx
src/screens/UserPortal/Events/Events.tsx

Redesigning and refactoring
Fixes #1893 
https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/dfb1e300-eed1-4e8c-a10c-ff2c94fa2bde
**Summary**

User Calender Revamp 

---

src/GraphQl/Mutations/mutations.ts
src/screens/OrganizationPeople/AddMember.tsx
src/screens/OrganizationPeople/OrganizationPeople.test.tsx

BugFix
Fixes #1905 
Yes
**Summary**
Add new member in the people screen was not working earlier, now it is fixed in this PR.
No

fixed the add new member error in People screen

---

src/GraphQl/Queries/OrganizationQueries.ts
src/components/Venues/VenueModal.tsx
src/screens/OrganizationVenues/OrganizationVenues.test.tsx
src/screens/OrganizationVenues/OrganizationVenues.tsx

bugfix, feature
Fixes #1910 
Yes 
https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/9ef2b787-5129-4168-9587-f7376bdb25f6
**Summary**
- Implemented `GetVenueByOrgId` resolver for server-side sorting/filtering.
- Updated tests
- Fixed persistent form state even after successful mutation bug.
No
Yes

Updated Venue Resolver for Server-side Sorting/Filtering

---

public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
src/screens/OrganizationFundCampaign/CampaignUpdateModal.tsx
src/screens/OrganizationFundCampaign/OrganizationFundCampagins.tsx
src/screens/OrganizationFundCampaign/OrganizationFundCampaign.module.css
src/screens/OrganizationFundCampaign/OrganizationFundCampaign.test.tsx

Fundraising Campaigns screen re-designed
Fixes #1753
yes
NA
**Summary**
No
NA
Yes

ADMIN Redesign: Fundraising Campaigns 

---

src/screens/OrganizationFunds/OrganizationFunds.tsx

Minor fix
Ref #1753
NA
NA
**Summary**
Only added **text color** and **pointer**

Text color and pointer

---

src/App.tsx
src/components/EventDashboardScreen/EventDashboardScreen.module.css
src/components/EventDashboardScreen/EventDashboardScreen.test.tsx
src/components/EventDashboardScreen/EventDashboardScreen.tsx
src/screens/EventManagement/EventManagement.test.tsx
src/screens/EventManagement/EventManagement.tsx

BugFix
Fixes #1912 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/2ebf577e-3e1d-4c24-9d15-e9259382f091
**Summary**
Regular user can now have the access to the event dashboard for the event created by them.
No
Yes

Regular users can access the dashboard of the event created by them

---

src/GraphQl/Mutations/mutations.ts

refactor
Fixes #1974 
Yes 
**Summary**
Updated createAdmin Mutation
No
Yes

Fixed Introspection fail

---

src/components/EventManagement/EventActionItems/EventActionItems.module.css
src/screens/OrganizationPeople/OrganizationPeople.module.css

Bugfix
Fixes #1862 
No, not required.
No
**Summary**
Removed the border that overlapped with the label.
No
None
Yes

Bug Fix of event border

---

package-lock.json
package.json

Reverts PalisadoesFoundation/talawa-admin#2034

Revert "chore(deps): bump eslint-plugin-jest from 25.7.0 to 28.6.0"

---

src/components/Advertisements/Advertisements.test.tsx

Reverts PalisadoesFoundation/talawa-admin#2705

Revert "convert from jest to vitest #2486"

---

.eslintrc.json
scripts/githooks/check-localstorage-usage.js

Reverts PalisadoesFoundation/talawa-admin#3186
This change seems to be affecting our PR process
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/12694729705/job/35385141042?pr=3225

Revert "BugFix : Fixed failing ESLint and Prettier tests in scripts/githooks/check-localstorage-usage.js file"

---

src/components/UserListCard/UserListCard.spec.tsx
src/components/UserListCard/UserListCard.tsx

Reverts PalisadoesFoundation/talawa-admin#3230
The PR had to be reverted.
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/12855755706/job/35841668724?pr=3309

Revert "Improved Code Coverage of UserListCard.tsx"

---

src/style/app.module.css

Updated incorrect color names

---

src/subComponents/SearchBar.spec.tsx

Bug Fix
Fixes #3669
NA
**Summary**
The code coverage for `SearchBar.tsx` was lower than the acceptable standards of the repository. I have added tests to make sure that the code coverage reaches full 100%.
No
- [ x] I have written tests for all new changes/features
- [ x] I have verified that test coverage meets or exceeds 95%
- [ x] I have run the test suite locally and all tests pass
NA
Yes

Improving the Code Coverage in SearchBar.tsx to 100%

---

.coderabbit.yaml
.github/dependabot.yaml
.github/workflows/pull-request.yml
.github/workflows/push-deploy-website.yml

Fixed old develop-postgres references

Fixed old develop-postgres references

---

docs/README.md
docs/docs/docs/getting-started/configuration.md
docs/docs/docs/getting-started/login.md
docs/docs/docs/getting-started/webserver.md

Added Apache configuration
