CONTRIBUTING.md
Updated the  `CONTRIBUTING.md` to include the alpha and develop branches
=> Updated CONTRIBUTING.md with new branching strategy

.github/workflows/codeql-analysis.yml
…ll branches in pull request
Fixes #62 
**Summary**
1. disabled CodeQL github actions on 'push'
2. removed cron jobs
3. configured it to run on pull request on all branches.
4. related issue #62 
No
Yes
=> Code -QL configuration to run on every pull request on all branches

src/components/AdminNavbar/AdminNavbar.tsx, src/screens/OrgList/OrgList.module.css, src/screens/OrgList/OrgList.tsx
Add a button on the /orglist page to logout user and redirects to login page i.e /
Fixes #180  
No.
**Summary**
Currently, there is no logout option on the site, except the one that logs the user out of the manage organization page.
If a user wants to log out he has to manually go to the '/' route and the local storage is cleared which is not a widely used logout flow.
No.
Yes.
=> Add button to logout user

src/components/LandingPage/LandingPage.test.tsx, src/components/LandingPage/LandingPage.tsx
This PR adds unit tests for the landing page under a single test suite
Related to issue #157 
Tests run:
1). yarn test
2). yarn serve
3). yarn lint
=> Added Unit tests for Landing Page

src/components/AdminNavbar/AdminNavbar.test.tsx, src/components/AdminNavbar/AdminNavbar.tsx, src/screens/OrganizationDashboard/OrganizationDashboard.test.tsx
Bugfix
Fixes #214 
No
No
**Summary**
While rendering components from the navigation bar page is reloading. Instead of just rendering the component, which is not a good user experience. The user expects, when someone clicks on a navigation link, only the component is loaded instead of the whole page.
No
Nil
Yes
=> Rendering of components fixes

package.json, src/screens/OrgList/OrgList.test.tsx
Adds Unit tests for Organisations People Page
FIxes #165 ,  
Also in reference to #157 
1). Tests whether correct mock data is queried or not
2). Two mock objects created for two useQueries (1 for each) :- 
a). `Organisations People Page`
b). `ORGANIZATION_LIST`
3). Tests whether content is rendered on DOM or not
4). Tests whether correct content is labelled or not
5). Updates package `jest-docblock` to avoid errors during testing
Future tests possible:-
1). Testing Create Mutation
=> Unit tests for testing Organisations People Page

src/components/EventListCard/EventListCard.tsx, src/components/MemberRequestCard/MemberRequestCard.tsx, src/components/OrgAdminListCard/OrgAdminListCard.tsx, src/components/OrgPeopleListCard/OrgPeopleListCard.tsx, src/components/SuperDashListCard/SuperDashListCard.tsx, src/components/UserListCard/UserListCard.tsx
bugFix
Fixes #218 
Instead of nesting `<p> tags inside a <p> tag` , empty tag (equivalent of React.Fragment has been used)
There is no change caused in UI and the warnings have been resolved
Yes
=> Fix yarn test warning of paragraph tag nesting

.github/workflows/codeql-codescan.yml, .github/workflows/pull-requests.yml, .github/workflows/push.yml
Created a seperate workflow file for codeQL that will have branches for both `on.push` and `on.pull-request` instances and will fix all codeQL warnings 
bugFix
Fixes #210 
YEs
=> Add a seperate CodeQl workflow file to perform all workflows without errors

src/screens/OrgSettings/OrganizationDashboard.test.tsx
Testing
**Description**
Adds Unit Tests for Organisation Settings Page
1). Mock data for useQuery on `MEMBERSHIP_REQUEST`
2). Testing whether Mock Data is correctly queried or not
3). Testing container content matching
Fixes #162 
Also in reference to #157 
Also increases test code coverage by 1.83%  to a total of `24.25%`
Yes
Yes
=> Unit Tests for Organisation Settings Page

src/screens/OrganizationEvents/OrganizationEvents.test.tsx
Testing
Description
Adds Unit Tests for Organisation Events Page
1). Mock data for useQuery on `ORGANIZATION_EVENT_LIST`
2). Testing whether Mock Data is correctly queried or not
3). Testing container content matching
Issue Number:
Fixes #164 
Also in reference to #157
Also increases test code coverage to a total of 30.32%
Yes
=> Add tests for organisation events page

src/state/helpers/Action.test.ts
Fixes #282 
Yes
Not required.
**Summary**
Added tests for Action interface present in `src/state/helpers/Action.ts`
However, There is no code to cover here, since nothing is executable. 
The file has only one interface which only exist at compile-time not at runtime. 
But it will notify if the interface is wrongly initiated at build time.
No
Yes
=> Add tests for Reducer Action Interface

src/screens/LoginPage/LoginPage.module.css
Bug Fix  : Enabled Scrolling on register page
**Issue Number:** 290
Fixes #290 
No .   Only CSS was changed
Now a scrollbar will be visible if overflow
**Summary**
No 
Yes
=> 🐛 FIX: Enabled Scrolling On register page

src/state/index.test.ts, src/state/store.test.tsx
Note: this repeated PR from #299 due to some technical problems (you can visit #299 for more information)
Added Testcases for src/state/index.ts file
Issue Number:
#277 
Fixes #277 
Yes I have added a testfile
Summary
I have added a store.test.tsx file required for issue #277  for Gsoc2022
No
SnapShots
Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes
=> Test src test store

package.json, yarn.lock
Fixes #368 
No
Not Needed
Not Relevant
**Summary**
- Bumped `react-scripts` from `v5.0.0` to `v5.0.1`
- As per [documentation](https://github.com/facebook/create-react-app/releases), upgrading to `v5.0.1` doesn't cause any breaking changes
- Thus, no breaking changes
- All test cases passing
Yes
=> Bump react-scripts to v5.0.1

package.json, setup/utils/markdown.js
This PR solves a bug that caused unnecessary changes during the initial setup
Fixes  #372 
No
Not Relevant, the setup doesn't cause any files to change now.
Not Relevant 
**Summary**
- In the `yarn setup` script, some packages are initially installed to carry out setup tasks
- These packages cannot be updated by the dependa-bot unlike in the `dependencies` object
- Thus, this [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/301/files) caused the bug by bumping the version of the `marked` package
- I've synchronized the versions of packages between the setup script and dependencies object.
- Also, …
=> Synchronised package versions

src/Constant/constant.ts, src/components/OrgDelete/OrgDelete.test.tsx
Fixes #409 
No
Not Relevant
**Summary**
- Added the `BACKEND_URL` constant
- The constant extracts value from the `REACT_APP_TALAWA_URL` environment variable
- Replaced the hard-coded reference to `talawa-graphql-api.herokuapp.com` with a new constant
No
- The other test cases directly access the `REACT_APP_TALAWA_URL` environment variable
- There is nothing wrong with this approach 
- But using a constant to extract the environment variable and later using the same constant in the different files is a better approach
- As it is easy to maintain …
=> Remove Heroku Reference from OrgDelete Tests

src/components/LandingPage/LandingPage.test.tsx
Fixes #410 
No
Not Relevant
**Summary**
- Replaced the hard-coded reference to `talawa-graphql-api.herokuapp.com` with a `BACKEND_URL` constant
No
None
Yes
=> Remove reference to heroku URL in LandingPage test

src/GraphQl/Mutations/mutations.ts
Fixes #370 
No
Error when creating a new organization -
The response returned from the server -
Not Relevant 
**Summary**
- The backend returned an error when creating a new organization with `tags`
- This was due type mismatch between frontend (`[String]`) and backend (`[String!]!`)
- I've fixed the GraphQL mutation query to match the backend
- Thus, the error has been resolved, I've added supporting screenshots below
No
New organization getting created with `tags` - 
All tests passing - …
=> Fix Org creation error

yarn.lock
a bugfix
Fixes #436 
not needed
The warning has been resolved and we have shifted to the latest version of cani-use lite
not needed
**Summary**
This PR resolves a warning message which used to appear when we use to test our code using "yarn test" in our local environment and hence closes #436 
No
Yes
=> fixed cani-use lite warning

.github/workflows/pull-requests.yml
Bug Fix
Fixes #432 
NA
NA
**Summary**
Moved the linting action to the linter section in the GitHub workflow file. Also changed the linting action to just check for the linting errors, instead of running and linting the code.
No
Yes
=> Move Linting action to Linter Section in GitHub Workflow [Fixes #432]

public/manifest.json, src/screens/OrgList/OrgList.tsx
**Issue Number**
FIXES #471
Before:
After:
No
**Summary**
I have updated the structure of DOM, which was causing this error. Also i have provided flexible size to logo192.png in manifest.json.
No
Yes
=> Removing all the Errors from console FIXES #471

src/GraphQl/Queries/Queries.ts, src/screens/BlockUser/BlockUser.test.tsx, src/screens/BlockUser/BlockUser.tsx, src/screens/OrganizationPeople/OrganizationPeople.test.tsx, src/screens/Requests/Requests.test.tsx, src/screens/Roles/Roles.test.tsx
Bug Fix
Fixes #371 
Not Needed
`Roles` and `Request` pages working fine -
The `OrganizationPeople`  page working fine -
The `Block/Unblock User` page working fine -
Not Relevant
**Summary**
- The `LIST_USER` query has a type mismatch between the frontend and backend
- The `spamInOrganisation` param was removed from the backend
- This causes many pages like `Roles`, `Request`, `OrganizationPeople `, `BlockUser`, and `AddOnStore` to fail
- I've removed the `spamInOrganisation` param from frontend and fixed the failing tests as result of it
- Also, removed mock data from other test files
**Does this PR introduce a …
=> Removed spamInOrganizations from User Query and Fixed Various Pages

public/locales/en.json, public/locales/fr.json, public/locales/hi.json, public/locales/sp.json, public/locales/zh.json, src/components/OrgPostCard/OrgPostCard.tsx, src/components/OrgUpdate/OrgUpdate.test.tsx, src/components/OrgUpdate/OrgUpdate.tsx, src/components/UserUpdate/UserUpdate.test.tsx, src/components/UserUpdate/UserUpdate.tsx, src/screens/BlockUser/BlockUser.tsx, src/screens/ForgotPassword/ForgotPassword.test.tsx, src/screens/ForgotPassword/ForgotPassword.tsx, src/screens/OrgContribution/OrgContribution.tsx, src/screens/OrgList/OrgList.test.tsx, src/screens/OrgList/OrgList.tsx, src/screens/OrgPost/OrgPost.test.tsx, src/screens/OrgPost/OrgPost.tsx, src/screens/OrganizationEvents/OrganizationEvents.tsx, src/screens/OrganizationPeople/OrganizationPeople.tsx
bugfix: added translation for the hint text
Fixes #455 
yes 
**Summary**
No
Not Any
Yes
=> Fixed #469 : Added translation for hint text in placeholder

public/locales/en.json, public/locales/fr.json, public/locales/hi.json, public/locales/sp.json, public/locales/zh.json, src/components/UserUpdate/UserUpdate.test.tsx, src/components/UserUpdate/UserUpdate.tsx
Bug fix, dropdown of app languages in user updation form 
#485 
Fixes #485
Yes
No necessary.
**Summary**
No
Yes
=> Added dropdown for Applanguage in UserUpdation form

.husky/pre-commit, INSTALLATION.md, package.json, yarn.lock
Add Husky to the codebase to improve developer experience.
Fixes #495 
NA
Yes
No
NA
Yes
=> Add Husky [Fixes #495]

src/components/EventListCard/EventListCard.test.tsx
Bug fix
Fixes #569
Yes
**Summary**
This rectifies the warning generated when running tests for the `EventListCard` component.
No
I got to find out that the warning from issue #569 is caused by `MockedProvider` because it renders the `MOCKS` twice. This causes the `No more mocked responses for the query` warning the second time it renders. This had been a recurring issue for apollo-client for a long time with no clear rectification. However, to stop the warning from showing up when running the test I used the `MockLink` class. …
=> Rectify Warnings: EventListCard.test.tsx [Fixes #569]

src/screens/OrganizationDashboard/OrganizationDashboard.module.css, src/screens/OrganizationDashboard/OrganizationDashboard.tsx
The PR fixes the organization description overflowing its container.
Fixes #604 
**Screenshot**
Before:
After:
**Summary**
The organization's description overflows its container and needed a change.
This PR solves that by breaking words when it is longer than it contains.
No
Yes
=> Fix about content overflow

src/screens/OrgPost/OrgPost.tsx
This pr was created to remove the duplicate rows per page section in orgposts.
Fixes #544
No
No
**Summary**
This issue was the duplication of pagination component. so my job was to remove the duplication of the component so that it doesn't confuses the users. 
No
Yes
=> removed duplicate rows per page section in orgposts

src/screens/OrganizationDashboard/OrganizationDashboard.module.css, src/screens/OrganizationDashboard/OrganizationDashboard.tsx
feature
Issue Number:
Fixes: #572
No
before:
after:
UI before:
UI after:
Summary
I moved organization location rendered on the same row as company name to the about section as sugested on issue #572
and removed duplicate orgName as instructed.
**Does this PR introduce a breaking change?
No
Other information
Have you read the contributing guide?
Yes
=> fixed:move orgLocation & remove duplicate orgName

src/screens/OrgList/OrgList.module.css, src/screens/OrgList/OrgList.tsx
This Pull request moves the search and the create organization button below the header
Fixes #633 
**Did you add tests for your changes?**`
No, it was a UI adjustment.
**Summary**
The Search organization input was moved to the top of the organization list header which wasn't aligned. This looked bad for UI and UX. I moved it under the Organization list header alongside the create organization button to favor UI and UX as well as made them responsive for mobile.
No
Yes
=> fix organization search input box location

src/screens/Roles/Roles.tsx
Bugfix
Issue Number:
Fixes #551
No
Summary
Summarily, whenever an user role update was performed by the superadmin, the role displayed remained the same whenever the he navigates out and back to the page, the replication procedure is detailed on issue #551
To solve this, i just added a refetch() expression after the success toast
No
Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes
=> User role ui not updating on change  - issue #551 resolved

src/components/AdminNavbar/AdminNavbar.module.css, src/components/AdminNavbar/AdminNavbar.tsx
This change adds a clear spacing to a navbar dropdown item.
Fixes #641 
Not required. Css style edits.
**Summary**
I have added the css style margin property for correcting the spacing between plugins dropdown and add organisation button in the navbar.
No
Yes
=> Fix:#641 Removed the Overlapping

src/components/OrgPostCard/OrgPostCard.test.tsx, src/components/OrgPostCard/OrgPostCard.tsx
Replaces input element with textarea in edit post dialog
Fixes #705 
Modified some tests
No
**Summary**
As information contains long text, it's appropriate to have text area for input and changing the value. In create post modal the text area field is being used, similarly update the edit post modal.
No
NA
Yes
=> changes input element to textarea and changes in test

src/components/AddOn/core/AddOnEntry/AddOnEntry.tsx, src/components/AdminNavbar/AdminNavbar.module.css, src/components/AdminNavbar/AdminNavbar.test.tsx, src/components/AdminNavbar/AdminNavbar.tsx
Eliminate huge white space on the Organization navbar by aligning all nav items to the center when the screen size is <=1199px and remove repetitive organization image at the bottom of the navbar and replace it with text "more" close to the drop down arrow.
- #748 
No
No
=> align navbar items

public/locales/en.json, src/screens/OrgList/OrgList.test.tsx, src/screens/OrgList/OrgList.tsx, src/screens/Requests/Requests.test.tsx, src/screens/Requests/Requests.tsx, src/screens/Roles/Roles.test.tsx, src/screens/Roles/Roles.tsx
Feature/Refactoring
Fixes #533 
Yes
`OrgList` Page -
`Roles` Page -
`Request` Page -
Not Relevant
**Summary**
- The `SUPERADMIN` pages did not give any error or warning when organizations were absent
- This caused bad UX on Talawa mobile app
- Added a persistent alert on the `OrgList` page 
- And warning toasts in the `Roles` and `Request` pages
- Added Tests for new changes
No
NA
Yes
=> Super Admin Dashboard Error When Organizations Absent

src/components/AdminNavbar/AdminNavbar.test.tsx, src/components/AdminNavbar/AdminNavbar.tsx, src/components/ListNavbar/ListNavbar.module.css
Eliminate huge white space on the super admin navbar by aligning all nav items to the center when the screen size is <=1199px, This white space makes the navbar look incomplete, It can lead to poor user experience.
Fixes  
- #757 
No.
**Summary**
=> Align superadmin navbar

package.json, src/components/PaginationList/PaginationList.tsx, src/screens/Roles/Roles.test.tsx, src/screens/Roles/Roles.tsx
While searching for users by their first name in the Roles page, it will show the appropriate results instead of showing results for the previous input. ( it was giving results an input variable behind )
Fixes #716 
No
https://user-images.githubusercontent.com/97829544/225826006-9d54dda3-a849-4cb6-aa2c-9cceac6f02d8.mp4
Not Relevant.
**Summary**
While searching for users by their first names in the Roles section of talawa admin app, whenever we used to type input, it was showing the relevant results one step afterwards.
for example, If we typed 'f' , it wouldn't show the  users whose names have 'f' in their first …
=> changed the handleSearchByName function in searchByName in Roles page

src/components/EventCalendar/Calendar.test.tsx, src/components/EventCalendar/Calendar.tsx, src/screens/OrganizationEvents/OrganizationEvents.tsx
This PR Fixes:
- The ability to make events private where only participants can see who is attending
- The optional ability to make private events invisible to persons not attending
Fixes #795 
Yes
N/A
N/A
**Summary**
The participants in all events are publicly visible to everyone. There need to be options for more privacy.
No
Yes
=> Modify event visibility for non-admins

src/components/OrgUpdate/OrgUpdate.tsx
Bugfix 
Fixes #594 
Not needed
Not Relevant
**Summary**
- The `OrgUpdate` page just refreshed when the user updated an organization
- The expected behavior is that the user should be redirected to the `OrgDashboard` page
- So that they can view their updates
No
NA
Yes
=> Redirect to dashboard on organization update

src/assets/images/close.svg, src/screens/OrgList/OrgList.tsx
**Description**
**This PR addresses issue #808 , which reported a bug where the organization creation form is displayed on the same URL as the organization list page when the "Create Organization" button is clicked, making it difficult for users to navigate back to the organization list page or leave the form with any routing from the page.**
**Approach**
**To solve this issue, I added a "Close" button to the organization creation modal, allowing users to easily close the modal and return to the organization list page. Additionally, I implemented a way to close the modal when the user clicks on the overlay, which is a common pattern in modal-based UIs.**
Fixes #808
<br />
<br />
**Changes Made**
- **Added a closing icon SVG in './src/assets/images/close'.**
- **Added that Closing button …
=> Organization Form Redirect Issue Prevents User Navigation, Affecting User Experience.  Issue #808

src/screens/OrgList/OrgList.test.tsx, src/screens/OrgList/OrgList.tsx, src/screens/OrgPost/OrgPost.test.tsx, src/screens/OrgPost/OrgPost.tsx
Bugfix
Fixes #834 
Yes
Create Org -
Create Post -
Not Relevant
**Summary**
- The Organization and Post create forms had compulsory text fields
- But the user could simply add empty strings (`"    "`)  and bypass the `required` validation
- I've fixed this issue by giving an error message on submit
No
NA
Yes
=> Added Whitespace Validation to Organization and Post create forms

src/screens/Roles/Roles.test.tsx, src/screens/Roles/Roles.tsx
Bugfix
Fixes #764 
Yes
Not Relevant
**Summary**
- There is a feature that allows `SUPERADMINS` and `ADMINS` to downgrade their roles
- This can be dangerous as they could get locked out of the system 
- If they are the only users with that high level of access
- Thus, I've disabled the users changing their own roles
- This ensures they don't get locked out of the system
No
NA
Yes
=> Prevent Admins and Super Admins from downgrading their own roles

public/locales/en.json, public/locales/fr.json, public/locales/hi.json, public/locales/sp.json, public/locales/zh.json, src/GraphQl/Queries/Queries.ts, src/screens/OrganizationPeople/OrganizationPeople.test.tsx, src/screens/OrganizationPeople/OrganizationPeople.tsx
Bug Fix
Fixes #730 
Yes
Not Relevant
**Summary**
The problem -
- The Organization People's page filter didn't work as intended
- The user couldn't search by `lastName`
- The filters didn't work for `users` and `admins`
- The page unnecessarily reloaded after a change in the search query
Changes -
- Added a new field to search by `lastName`
- Added filters to `users` and `admins` as well
- The complete page no longer reloads
- Only the table reloads  
No
NA …
=> Organization People Filters Improved

src/screens/OrgList/OrgList.test.tsx, src/screens/OrgList/OrgList.tsx
This PR restores the test for search-bar of the OrgList Page.
Fixes #870 
**Screenshots**
Codecov Report -
Tests are written analogous to tests for search-bar in other pages which have the same code.
Search-bar Roles Page -
Search-bar Request Page - 
Search-bar BlockUser Page - 
Yes
Yes
=> Restored Search-Bar Test for OrgList Page

src/components/EventCalendar/Calendar.module.css, src/components/EventCalendar/Calendar.test.tsx, src/components/EventCalendar/Calendar.tsx
Features : 
- A today button in calendar on clicking it the calendar will  focus on today's date.
- User can go to current month with single click  instead of manually switching months
- Highlighting of today's date in month
- Shadowing of days which are not in the month
Fixes #883 
YES
https://user-images.githubusercontent.com/103348863/233394659-b9669b25-6e90-47ae-9597-731cd3b3115f.mp4
N/A
N/A
N/A
YES
=> Add today functionality in calendar

src/GraphQl/Mutations/mutations.ts, src/components/AdminNavbar/AdminNavbar.test.tsx, src/components/AdminNavbar/AdminNavbar.tsx, src/components/AdminNavbar/AdminNavbarMocks.ts
Bugfix
Fixes #945 
Not required
Not applicable
Not applicable
**Summary**
Keeping our frontend mutations in sync is necessary.
- `updateSpamNotification` mutation was not in `talawa-api` and notification modal was not working, so i have removed them in order to make the backend in sync with `talawa-admin`
No
None
Yes
=> Make Talawa-Admin mutations in sync with the backend

src/components/EventStats/Statistics/AverageRating.test.tsx, src/components/EventStats/Statistics/AverageRating.tsx, src/components/EventStats/Statistics/Feedback.tsx, src/components/EventStats/Statistics/Review.tsx
Bugfix
Fixes #990 
Yes
NA
NA
**Summary**
As discussed with @palisadoes, the maximum feedback rating in event management should be `5` to maintain consistency. This PR updates the same to be 5 instead of 10. 
No
NA
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes
=> Move maximum rating in feedback from 10 to 5 [Fixes #990]

src/components/EventCalendar/EventCalendar.tsx, src/screens/OrganizationEvents/OrganizationEvents.tsx
Now the modal is automatically closed after the successful creation of the event and also the events are automatically updated in the calendar. I have attached a video demonstrating the flow.
Fixes #1011 
https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/e6d1cc6c-d260-4b58-a701-e1f44c967509
**Summary**
Previously, upon successful event creation, the modal wouldn't close automatically, requiring manual closing of the modal. Additionally, events weren't reflected in real-time, we need to refresh to view newly added events.These issues are now solved. I've fixed the modal closing issue and …
=> Fix modal closing and automatically updating events without refresh.

src/components/EventListCard/EventListCard.module.css, src/components/EventListCard/EventListCard.test.tsx, src/components/EventListCard/EventListCard.tsx
Bugfix
Fixes #1013 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/8022d493-bb8a-49a2-b4ac-eb6fdd1083e6
**Summary**
Previously, the update and delete buttons in the event modal were non-functional. In this pull request, I've addressed this issue and resolved the bug to ensure their proper functionality.
No
=> update and delete buttons of event modal are now working

src/screens/OrganizationEvents/OrganizationEvents.test.tsx, src/screens/OrganizationEvents/OrganizationEvents.tsx
A bug.
Fixes #1021 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/edc731eb-d87f-480b-85e4-3631cba75bf0
**Summary**
Previously events can be created with white spaces only. To fix this issue I have added a validation that if the title, description or the location has values with white spaces only than It will show a warning. I have attached a video for the same showing that.
Now user can't create an event with white spaces and no text.
No …
=> Fix event creation issue with white spaces.

src/components/EventListCard/EventListCard.module.css, src/components/EventListCard/EventListCard.test.tsx, src/components/EventListCard/EventListCard.tsx, src/components/LeftDrawerEvent/LeftDrawerEvent.test.tsx, src/components/LeftDrawerEvent/LeftDrawerEvent.tsx, src/screens/EventDashboard/EventDashboard.module.css, src/screens/EventDashboard/EventDashboard.tsx
UI/UX changes, bug fix.
Fixes #1022 
https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/ddf888a9-82fe-4938-82c3-01694b4ccd36
**Summary**
The title of the event is now truncated and when we hover over the title then we can see the title of the event upto 150 characters. In eventDetails modal , the title is truncated to 150 characters and the description is truncated to 256 characters. Also in the event dashboard page, near the event name logo, the title is truncated to 25 characters and descritpion is truncated to 30 characters. Along with that , in the event dashboard page there are minor …
=> Fix layout distortion due to untruncated title description of events.

src/components/LeftDrawerEvent/LeftDrawerEvent.test.tsx, src/components/LeftDrawerEvent/LeftDrawerEvent.tsx
BugFix
Fixes #1050 
Yes
**Summary**
Event dashboard page don't have any option to return back to events page of the organization. So, in this PR I have created a **All Events** button which redirect the user to the events page of the organization.
No
=> Created a all events button on event dashboard

src/components/Loader/Loader.test.tsx
- Improved the test coverage for the Loader component, addressing the previously uncovered lines and ensuring that all tests pass successfully.
- Added a test to ensure that the component renders correctly with a custom 'sm' size. I verified that both the spinner-wrapper and spinner elements are present and that the correct class is applied.
- Added a test to ensure that the component renders correctly with a 'lg' size. I verified that the spinner element has the appropriate class.
- Added a test to ensure that the component renders correctly with an 'xl' size. I verified that the spinner element has the correct class.
Fixes  #1026 
Yes
**Before**
**After**
**If …
=> test: Loader Component 100% Test Coverage and Fix Uncovered Lines

src/components/CheckIn/CheckInModal.test.tsx, src/components/CheckIn/CheckInModal.tsx, src/components/CheckIn/CheckInWrapper.test.tsx
Bug fix
Fixes #1012 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/2b7f8c5b-c822-426d-b5fc-252ce98dee3e
**Summary**
After adding a new registrant to an event, the change was not automatically reflecting in the event check-in management. We need to refresh the page. Now after fixing the bug it will be reflected immediately.
No
=> Fixed event check in management not updating automatically bug

src/components/UserPasswordUpdate/UserPasswordUpdate.test.tsx
- Improved the test coverage for the User-Password-Update component, addressing the previously uncovered lines and ensuring that all tests pass successfully.
- Added two new tests
1. Empty Password Field Test:
- The first test ensures that an error is displayed when attempting to save changes with an empty password field.
2. Mismatched New and Confirm Passwords Test
- The second test covers the scenario where the new and confirm password fields do not match.
Fixes #1030 
Yes
**Summary**
With these new tests, I now have 100% test coverage, and there are no more uncovered lines.
**Have you …
=> test: Achieved 100% test coverage and fixed uncovered lines

src/components/LeftDrawerEvent/LeftDrawerEventWrapper.test.tsx
Update test for LeftDrawerEventWrapper.tsx to 100% coverage.
Fixes #1033
**Summary**
Added tests which covers line 40, where pageContainer was not previously tested for 'expand' or 'contract' class. 
No
Chose to use Regex because pageContainer classes somehow had extra suffix added in like "_pageContainer_1k3kw_1" which .toHaveClass method cannot assert properly. 
Yes
=> Update test for LeftDrawerEventWrapper.tsx to 100% coverage

src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.tsx
- Before 
- Upon deleting the advertisement, it is expected to be removed from the backend and no longer displayed on the frontend. However, despite deletion on the backend, the advertisement continues to appear on the frontend.
- After
- Now Deletion will reflect to both frontend and backend
Fixes #1109 
- No
- Before 
[Delete_Bug.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/f8671b76-b3eb-4b4b-948f-79854babfee8)
- After
[Fixes_Delete_bug.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/239ceedd-5bd9-4e3f-8769-2b8614c61d74)
**Summary**
- Now when user will …
=> Bug Fix: Frontend now reflects advertisement deletion, aligning with backend.

src/GraphQl/Queries/Queries.ts
Bug fix
Fixes #1121
[www_screencapture_com_2023-12-5_17_12.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/18a10c60-6c89-4844-b186-0fa07e3521cd)
**Summary**
The query to fetch all the posts for an organization was missing pinned attribute.
Added the "pinned" in the query.
=> Fixed the bug in pinned post functionality

CONTRIBUTING.md
**Issue Number:** #1095 
Fixes #
**Summary**
=> Setting Up Codecov Environment (Documentation Update)

src/components/OrgPostCard/OrgPostCard.tsx
Image or Video used to automatically removed if user wants to update other fields in Post.
Fixed removing of image or videos if user doesn't want to update or remove image or videos.
Fixes #1110 
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/71c5a1ba-19ec-499b-b04d-ba7fb5f63272
**Summary**
Post used to update with null fields of images or videos, if user doesn't reupload it. Now query will not send null fields of images or videos.
No
Yes
=> fix: Update post removes photos or videos

src/components/OrganizationDashCards/CardItem.test.tsx
Updated test for src/components/OrganizationDashCards/CardItem.tsx
Fixes #1135 
Yes
No
Yes
=> Code Coverage: Updated test for src/components/OrganizationDashCards/CardItem.tsx

src/components/OrgListCard/OrgListCard.test.tsx
Fixes #1067 
Yes
**Summary**
This PR achieved the 100% test coverage of src/components/OrgListCard/OrgListCard.tsx
No
Yes
=> achieved test coverage for OrgListCard.tsx

src/screens/Requests/Requests.test.tsx, src/screens/Requests/Requests.tsx, src/screens/Requests/RequestsMocks.ts
Improves test coverage
Fixes #1044
=> Better test coverage for src/screens/Requests/Requests.tsx

src/screens/OrganizationDashboard/OrganizationDashboard.tsx, src/screens/OrganizationPeople/OrganizationPeople.tsx
Bugfix
Fixes #1126 
[www_screencapture_com_2023-12-9_04_32.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/4b40a760-1c65-4159-8eb3-90e4bed3aa79)
**Summary**
Earlier on clicking on the admin card the user was navigated to members section in Talawa Members. Fixed the navigation to direct it to admin section in Talawa Members.
Yes
=> Fixed admin card navigation in dashboard

src/components/EventRegistrantsModal/EventRegistrantsModal.tsx
Fixed overflow of event registrants in modal
Fixes #1148 
No
- Before
- After
No
**Summary**
Added scrollbar to scroll through the list.
No
Yes
=> fix: Fixed overflow of event registrants

src/GraphQl/Queries/Queries.ts, src/components/IconComponent/IconComponent.test.tsx, src/components/IconComponent/IconComponent.tsx, src/components/OrganizationScreen/OrganizationScreen.tsx, src/state/reducers/routesReducer.test.ts, src/state/reducers/routesReducer.ts
This PR renames the "All Organizations" button to "My Organizations" and fixes its postion as specified in the issue.
Fixes #1123 
No
[Screencast from 05-12-23 03:14:37 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/132701661/543631e7-37ba-4527-a0f6-be5c8ccda093)
No
**Summary**
This pull request addresses the specified issue by renaming the "All Organizations" button to "My Organizations" and adjusting its position to enhance the UI/UX.
No
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master …
=> [#1123] Changes position and text of "All Organizations" button

src/components/UserUpdate/UserUpdate.module.css, src/components/UserUpdate/UserUpdate.tsx
Refactoring code of User update page.
Fixes #1176 
Not yet.
before:
after:
NO.
**Summary**
As you can see in the before picture, the UI needed some improvements. I have made those improvements, and you can see the changes in the after picture.
NO.
Yes.
=> UI improvements in User Update page

src/components/DeleteOrg/DeleteOrg.test.tsx
Fixes #1066 
Yes
**Summary**
-Objective: This test ensures that the DeleteOrg component handles deletion failure gracefully when attempting to delete an organization.
- Objective: This test verifies that the DeleteOrg component closes the Delete Organization Modal when the "Cancel" button is clicked.
- Objective: This test confirms that the DeleteOrg component opens the Delete Organization Modal when the "Delete" button is clicked.
- Objective: This test ensures that the  DeleteOrg component correctly renders the Delete button based on specified conditions.
**Other …
=> Test for code Coverage For DeleteOrg.tsx

src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx, src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx
- Resolves the bug where the page was refreshing unexpectedly upon creating a new advertisement in the Advertisement Section.
Fixes #1115 
- No
- Before 
[cinnamon-2023-12-02T215527+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/1e4b369f-5636-41ea-8951-4286d36d6cb8)
- After
[cinnamon-2023-12-02T223826+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/81ba3e40-4971-4caa-8f03-4ffd431441af)
- No 
**Summary**
- The current issue in the Advertisement Section involves an unexpected page refresh after creating a new advertisement. This behavior is attributed …
=> Bug Fixes : On Creating advertisement page get reloaded 

src/components/Advertisements/Advertisements.test.tsx, src/components/Advertisements/Advertisements.tsx
Added tests for src/components/Advertisements/Advertisements.tsx
Fixes #1130 
**Summary**
I have added tests for the file. I 
No
I have also added an ignore statement in the file due to one function being declared, but not being used.
Yes
=> Added tests for src/components/Advertisements/Advertisements.tsx

src/index.tsx
bugfix, feature request
Fixes #1197 
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/121512095/cac44b7d-8c1d-4e10-95d0-469f5df0e933
No
**Summary**
this change adds a toast/dialog whenever the API server connection is down during login or user session for both the portals
No
N/A
Yes
=> Add a dialog/toast when the API is unavailable, both at login and during the login session for both portals

src/components/NotFound/NotFound.module.css
Fixes #1259 
Added some css to make the design uniform.
**Summary**
No
I incorporated this design because it is also used in organization serch and elsewhere on the website when no elements related to the search are found, contributing to a uniform website design.
[Screencast from 2023-12-23 21-32-00.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/4e06bf6a-7ed1-4c07-b73a-388fa5442095)
=> Fixed-Issue-#1259 Keeping the message in design when no posts is found.

src/screens/BlockUser/BlockUser.test.tsx, src/screens/BlockUser/BlockUser.tsx
- This PR addresses a bug in the Talawa dashboard where clicking on the blocked user card from the dashboard navigates to the wrong section (all members screen instead of the blocked user screen) in the block/unblock section.
Fixes #1120 
- Yes
- Before  : It navigate directly to all members
[cinnamon-2023-12-23T011117+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/59591c41-9a2a-4264-812a-f32419b62d40)
- After : It navigate to blocked members
[cinnamon-2023-12-23T011015+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/2736c9a0-ba45-46c2-937f-a75ea4608e44)
**If relevant, did you update the …
=> Bug Fixes: Fix in blocked user card navigation

public/locales/en.json, public/locales/fr.json, public/locales/hi.json, public/locales/sp.json, public/locales/zh.json, src/components/IconComponent/IconComponent.test.tsx, src/components/IconComponent/IconComponent.tsx, src/components/LeftDrawer/LeftDrawer.test.tsx, src/components/LeftDrawer/LeftDrawer.tsx, src/screens/OrgList/OrgList.tsx, src/state/reducers/routesReducer.test.ts, src/state/reducers/routesReducer.ts
This PR renames the "All Organizations" button to "My Organizations" and fixes its postion as specified in the issue.
Issue Number: #1123 
Fixes https://github.com/PalisadoesFoundation/talawa-admin/issues/1123
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/132701661/d7d35876-8f97-4bc9-84d6-7757f0fa7979
No
Summary
This pull request addresses the specified issue by renaming the "All Organizations" button to "My Organizations" and adjusting its position to enhance the UI/UX.
No
Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING. …
=> Fixed postion of 'All Organizations' button and changed its name

src/screens/MemberDetail/MemberDetail.test.tsx, src/screens/MemberDetail/MemberDetail.tsx
Removes a button which has no functionality
Fixes #1221 
I modified the test cases to incorporate the change
**BEFORE -**
**AFTER -**
NA
No
Yes
=> A button without any functionality

.github/workflows/pull-requests.yml
- This pull request standardizes TypeScript GitHub Action workflows by introducing two dedicated jobs: Code-Quality-Checks and Test-Application. The Code-Quality-Checks job handles  performing linting, formatting checks and type-error check while the Test-Application job, reliant on the former, focuses on testing the application. This change enhances workflow organization, promoting clear separation of code quality and testing concerns for improved maintainability.
Fixes #1277 
- No
**Summary**
- This PR standardizes TypeScript workflows with two jobs: Code-Quality-Checks for linting, formatting, and package …
=> Feature : Standardize the Pull Request GitHub Action to match Talawa API

src/components/EventStats/EventStats.module.css, src/components/EventStats/EventStats.tsx
Bug Fixes
**Issue Number:** 
Fixes #1286 
**Summary**
=> Improper positioning of Event Statistics in the mobile view 

public/locales/en.json, public/locales/fr.json, public/locales/hi.json, public/locales/sp.json, public/locales/zh.json, src/screens/UserPortal/Settings/Settings.module.css, src/screens/UserPortal/Settings/Settings.test.tsx, src/screens/UserPortal/Settings/Settings.tsx
Redesign Talawa User Portal Settings Page to Match Admin Portal Design
Fixes #1306
No, the tests are up to date for the changed files.
- Before
- After
https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/164d1fe3-415f-404e-bef2-4b79eed902b1
No
**Summary**
- Changed background colors
- Improved margin and paddings
- Improved width of input tags and form
No
Yes
=> Redesign talawa user portal settings page

src/screens/OrgPost/OrgPost.tsx, src/screens/Users/Users.tsx
- This PR addresses a bug in the Talawa dashboard where clicking on the sort button in the users and posts page doesn't show the selected sorting option in the button.
Fixes #1297 
All Test cases passed
https://github.com/PalisadoesFoundation/talawa-admin/assets/100997409/b02f29ed-f3e9-49d4-938d-b17caefccd5f
**Summary**
In the Users & Posts pages, when we use the sort functionality it doesn't show the currently selected sort option which creates confusion. So the proposed solution in the Pull Request (PR) aims to fix this by displaying the current sort option selected.
No
**Have you read the …
=> fix: sort button not displaying the selected option (#1297)

.github/workflows/compare-translational-files.py, .github/workflows/compare_translations.py, .github/workflows/pull-requests.yml, INSTALLATION.md, public/locales/fr.json, public/locales/hi.json, public/locales/sp.json, public/locales/zh.json
*Added GitHub workflow for comparing translation files*
Fixes #1185 
**Summary**
In this PR, I have introduced a GitHub workflow and a Python script that will check all the translation files and reflect the comparisons between different language files with English one.
Yes
=> Added github-workflow for comparing translation file

src/screens/LoginPage/LoginPage.test.tsx, src/screens/LoginPage/LoginPage.tsx
- after the user is successfully registered, login tab is opened
Feature
Fixes #1343 
Yes
https://www.loom.com/share/060389b1e8c04dca935d05bfbe8784d5?sid=1087406d-319b-4dc4-b9bc-c2383a5cbddf
Not relevant
**Summary**
- When a new user is registered there's a toast about successful registration but user has to manually visit the login tab and then login.
- Now after a successful registration login tab is opened
No breaking change
Yes
=> feat: after successful registration login tab opened on login page

src/components/LeftDrawerEvent/LeftDrawerEvent.module.css, src/components/LeftDrawerEvent/LeftDrawerEvent.tsx, src/components/LeftDrawerEvent/LeftDrawerEventWrapper.module.css, src/components/LeftDrawerEvent/LeftDrawerEventWrapper.test.tsx, src/components/LeftDrawerEvent/LeftDrawerEventWrapper.tsx
- Implemented the same minimization method used in the main organization pages, ensuring a consistent user experience throughout the application.
Fixes #1240 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/05bfc843-9d58-45bb-adc2-677d40da121c
No
**Summary**
Now there is consistency in minimization of the left column navbar in event mangement screen.
No
Yes
=> Fixed Inconsistent Use of Icons to Minimize Left Column Navbar in Event Management Screen

src/screens/OrgList/OrgList.tsx
This PR fixes the reappearing of the login page after successfully logging in as the SuperAdmin. 
Fixes #1328 
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/68781f7f-1ce5-4602-a5b0-c2ba6a8be8d2
**Summary**
No
This issue exists because the setting of the bearer authentication header happens only once in the ```src/index.ts``` file when the page is freshly loaded or reloaded.
```js
const httpLink = new HttpLink({
uri: BACKEND_URL,
headers: {
authorization: 'Bearer ' + localStorage.getItem('token') || '',
},
});
```
So when …
=> Fixed login screen reappearing after successful login

src/components/LeftDrawer/LeftDrawer.module.css, src/components/LeftDrawer/LeftDrawer.test.tsx, src/components/LeftDrawer/LeftDrawer.tsx, src/components/LeftDrawerEvent/LeftDrawerEvent.module.css, src/components/LeftDrawerEvent/LeftDrawerEvent.test.tsx, src/components/LeftDrawerEvent/LeftDrawerEvent.tsx, src/components/LeftDrawerEvent/LeftDrawerEventWrapper.module.css, src/components/LeftDrawerEvent/LeftDrawerEventWrapper.test.tsx, src/components/LeftDrawerEvent/LeftDrawerEventWrapper.tsx, src/components/LeftDrawerOrg/LeftDrawerOrg.module.css, src/components/LeftDrawerOrg/LeftDrawerOrg.test.tsx, src/components/LeftDrawerOrg/LeftDrawerOrg.tsx, src/components/OrganizationScreen/OrganizationScreen.module.css, src/components/OrganizationScreen/OrganizationScreen.test.tsx, src/components/OrganizationScreen/OrganizationScreen.tsx, src/components/SuperAdminScreen/SuperAdminScreen.module.css, src/components/SuperAdminScreen/SuperAdminScreen.test.tsx, src/components/SuperAdminScreen/SuperAdminScreen.tsx, src/screens/OrgList/OrgList.test.tsx
This PR introduces the standardization of left drawer expansion and collapse through refactoring.
Fixes #1413 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/8f5d58cf-905d-441b-9bc2-bf4113289118
No
**Summary**
- Previously, screens with a width of <= 820px utilized the hamburger icon for left drawer handling.
- With this change, all screens, regardless of width, will now have a consistent left drawer handling method, which was previously exclusive to screens with a width > 820px.
- The superadmin screen, organization screen, and event dashboard screen are all affected by this change.
- …
=> refactor: standardized left drawer expansion/collapse methodology

src/components/Advertisements/Advertisements.tsx
bug fix
Fixes #1364
No
**Summary**
This PR fixes issue #1364 where Advertisement button was not getting highlighted. This was caused as wrong Screenname was passed from Advertisement.tsx making the screenname and name as unequal.
No
The code follows the coding standards and guidelines outlined in the contributing guide.
[x] This change has been made against the develop branch.
YES
=> Advertisement button in the left sidebar of talawa-admin dashboard not getting highlighted when active #1364

.github/workflows/pull-requests.yml
- It will fix the graph introspection that is currently failing.
Fixes #1429 
- No
**Summary**
- It will fix the graphql-introspection that is currently failing. However, we need to be alert about the fact that whenever we merge the develop branch of talawa-admin into the main branch, we must first merge the develop branch of talawa-api into main.
=> fixes graphql-introspection

.idea/.gitignore, .idea/inspectionProfiles/Project_Default.xml, .idea/modules.xml, .idea/talawa-admin.iml, .idea/vcs.xml, src/components/AddOn/support/services/Plugin.helper.ts
Bug Fix : Due to wrong port number uncaught runtime error was coming which was unable to fetch the data in first time for the solution I have replaced the port no. from 3005 to 3000.
Fixes #1369 
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/107995043/c1bf309f-eee7-49b0-b5d5-e7ba01fab97f
No
**Summary**
No
Yes
=> Bug fix: uncaught runtime error 

src/components/LeftDrawerOrg/LeftDrawerOrg.module.css
Fixed display Issues with Lengthy Organization Names
Fixes #1271 
NA
**Before-**
**After-**
Demo1-
Demo2-
NA
**Summary**
NA
No
NA
Yes
=> Display Issues with Lengthy Organization Names

src/components/EventListCard/EventListCard.module.css, src/components/EventListCard/EventListCard.tsx
- Refactors the buttons in the "Edit Events" modal.
Fixes #1299 
No
- Desktop view
- Tablet view
- Mobile view
**Summary**
- Ensured aligned buttons properly in the "Edit Events" modal by verifying their placement across all screen sizes.
No
Yes
=> fix: Proper alignment of buttons in edit events modal

package-lock.json, package.json
Bugfix.
Fixes #1227 
No
No
**Summary**
As the `left-pad` library was a package dependency of the `jest-enzyme` library, and since `jest-enzyme` was neither used nor mentioned in the entire codebase, I removed the `jest-enzyme` library to resolve the error `npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()`.
No
Yes
=> Fixed `left-pad` deprecation warning.

src/index.tsx, src/screens/OrganizationEvents/OrganizationEvents.module.css, src/screens/OrganizationEvents/OrganizationEvents.test.tsx, src/screens/OrganizationEvents/OrganizationEvents.tsx
This PR changes the event Time Picker and Date Picker to Material UI ones.
Fixes #1239 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/1f52197d-2695-44ac-bef5-89f6192c1a8d
**Summary**
This PR modernizes and makes the Date Picker and Time Picker more user friendly. 
No
I have added a global Material UI Theme in the index.ts file as well
Yes
=> Changed event date and time picker

schema.graphql, src/GraphQl/Mutations/mutations.ts, src/components/UserUpdate/UserUpdate.tsx
Bugfix
Fixes #1473 
No
https://github.com/PalisadoesFoundation/talawa-admin/assets/76838871/ee4be25e-0c2c-443c-80f8-3d32f536a13d
**Summary**
Solves the following issues:
1. When attempting to update a member's profile, it required changing the email ID.
2. Despite updating the profile, the member's actual profile remained unchanged. Instead, the user's (your) profile credentials w were updated to match the member's credentials.
Yes
=> Fixed #1473: Unexpected behavior when updation of talawa admin members profile.

.editorconfig
This pull request introduces a feature of an updated EditorConfig file. The EditorConfig file is a configuration file that helps maintain consistent coding styles across different editors and IDEs used in the project. By defining indentation styles, line endings, and whitespace conventions, the EditorConfig ensures that all developers working on the project follow the same coding standards.
In this update, I have refined the indentation styles and sizes specifically for TypeScript, JavaScript, JSX, and React files. The configuration enforces the use of spaces for indentation with an indent size of 2 spaces for TypeScript and JavaScript files. For JSX and React files, the same configuration is applied, ensuring a consistent coding style …
=> feat: added editorconfig

src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx, src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx
This PR solves the issue of Advertisements Date Issue.
#1485 
Yes
**Summary**
Now, the end date of the advertisement cannot be less than the start date.
**Snapshots**
No
Yes
=> Fixes: Advertisement End date can be earlier than Start date

src/components/OrgProfileFieldSettings/OrgProfileFieldSettings.test.tsx, src/components/OrgProfileFieldSettings/OrgProfileFieldSettings.tsx
BugFix: - Resolves an issue where pressing the "Enter" key while adding a custom field in the settings was triggering an error.
Fixes #1395 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/f3d1371b-8cc7-43ed-96db-acbe791cc136
No
**Summary**
- Modified the handling of form submission to ensure that the custom field is added successfully whether the "Submit" button is clicked or the "Enter" key is pressed.
- Ensured all the modified lines are covered by tests and no other functionality is affected.
No
**Have you read the …
=> fix: Fixed custom field submission on Enter key press

src/GraphQl/Mutations/mutations.ts, src/screens/OrgList/OrgList.tsx
This PR fixes the issue when loading more orgs in organization list data, the entire data refreshes. With this PR, instead of refreshing entire data, it only refreshes the newly fetched data through pagination.
Fixes #1359 
https://github.com/PalisadoesFoundation/talawa-admin/assets/52243229/f9127e5e-1135-4905-a5e8-196c15b0f56b
**Summary**
Yes
=> Fix orgList screen refreshing entire data on load more orgs

src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx, src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx
Now, While Editing an Advertisement, we cannot make the end date of an advertisement before the Starting date.
Fixes #1547 
Yes
No
Yes
=> Advertisement Date Error While Editing is Solved.

public/locales/en.json, public/locales/fr.json, public/locales/hi.json, public/locales/sp.json, public/locales/zh.json, src/components/Advertisements/Advertisements.test.tsx, src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.module.css, src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx, src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx, src/utils/linkValid.test.tsx, src/utils/linkValidator.ts
This PR introduces validation of link in the advertisements screen.
Fixes #1479 
Yes
https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/6817aba0-0e9d-4975-8f6a-a22a69b7f05d
Not relevant
**Summary**
- Implemented validation for the `formState.link` field to ensure that it represents a valid URL.
- Proper The validation checks have been added to prevent users from submitting arbitrary or invalid strings when creating a new advertisement.
- Added tests for the modified code.
- Ensured no other functionality or tests fail after the changes.
No
**Other …
=> feat: added validation for links in advertisement

src/App.tsx, src/GraphQl/Queries/OrganizationQueries.ts, src/GraphQl/Queries/PlugInQueries.ts, src/GraphQl/Queries/Queries.ts, src/components/Advertisements/Advertisements.test.tsx, src/components/Advertisements/Advertisements.tsx, src/components/UserPortal/UserSidebar/UserSidebar.test.tsx, src/components/UserPortal/UserSidebar/UserSidebar.tsx, src/components/UserUpdate/UserUpdate.test.tsx, src/screens/UserPortal/Home/Home.test.tsx, src/screens/UserPortal/Home/Home.tsx, src/screens/UserPortal/Organizations/Organizations.test.tsx, src/screens/UserPortal/Organizations/Organizations.tsx, src/screens/UserPortal/UserLoginPage/UserLoginPage.tsx
Refactoring
Fixes #1686 
Yes
**Summary**
Fixed the `UserPortal/Home.tsx` screen to support `develop-userTypeFix` branch of talawa API
No
=> Fixed the UserPortal/Home.tsx for develop-userTypeFix branch

src/components/ActionItems/ActionItemsContainer.tsx, src/components/ActionItems/ActionItemsModalBody.tsx, src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx, src/components/OrgActionItemCategories/OrgActionItemCategories.tsx, src/components/OrgPostCard/OrgPostCard.tsx, src/components/UserPortal/UserSidebar/UserSidebar.tsx, src/screens/OrganizationActionItems/OrganizationActionItems.tsx, src/screens/OrganizationDashboard/OrganizationDashboard.tsx, src/screens/OrganizationFundCampaign/OrganizationFundCampagins.tsx, src/screens/OrganizationFunds/OrganizationFunds.tsx, src/screens/OrganizationPeople/AddMember.tsx
Change error logs to show `error.message` only
Fixes #1788 
Not required
=> fix: change error logs to show `error.message` only

src/components/LeftDrawerEvent/LeftDrawerEventWrapper.module.css, src/components/LeftDrawerEvent/LeftDrawerEventWrapper.tsx, src/screens/EventDashboard/EventDashboard.mocks.ts, src/screens/EventDashboard/EventDashboard.module.css, src/screens/EventDashboard/EventDashboard.tsx
A redesign.
Fixes #1749 
No.
**Summary**
In the following PR, I have redesigned the Event's dashboard screen for the talawa admin portal according to the figma file [here](https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1)
No.
Yes.
=> Redesigned the Event Management's Dashboard tab for the talawa admin portal

public/locales/en.json, public/locales/fr.json, public/locales/hi.json, public/locales/sp.json, public/locales/zh.json, src/components/UsersTableItem/UserTableItem.test.tsx, src/components/UsersTableItem/UsersTableItem.tsx, src/screens/Users/Users.tsx
This PR is a bug fix.
Fixes #1799 
Yes
[removed_drop_down.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/116624667/9b4fc421-f16b-498e-bf60-f9b83912545d)
Updated users page:
NA
**Summary**
- The drop down present on the `users page` was of no use as we are now following _per-organization policy_. I removed the drop down.
- The `Superadmin` can now edit the user roles from within the modals present on the `users page`.
No
Yes
=> Fix: Removed unnecessary drop down from the users page

src/screens/OrganizationActionItems/ActionItemUpdateModal.test.tsx, src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx
Added tests for src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx 
Fixes #1783 
NA
NA
NA
**Summary**
Added tests for src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx 
NA
NA
Yes
=> Added tests for src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx 

public/locales/en.json, public/locales/fr.json, public/locales/hi.json, public/locales/sp.json, public/locales/zh.json, schema.graphql, src/GraphQl/Mutations/mutations.ts, src/GraphQl/Queries/Queries.ts, src/components/UserPortal/Login/Login.test.tsx, src/components/UserPortal/StartPostModal/StartPostModal.test.tsx, src/components/UserPortal/UserSidebar/UserSidebar.test.tsx, src/components/UsersTableItem/UserTableItem.test.tsx, src/screens/LoginPage/LoginPage.test.tsx, src/screens/LoginPage/LoginPage.tsx, src/screens/MemberDetail/MemberDetail.test.tsx, src/screens/MemberDetail/MemberDetail.tsx, src/screens/OrganizationPeople/MockDataTypes.ts, src/screens/OrganizationPeople/OrganizationPeople.test.tsx, src/screens/Users/Users.tsx, src/screens/Users/UsersMocks.ts, src/utils/interfaces.ts
refactoring
Fixes #1845 
**Summary**
=> removed adminApproved field

src/screens/OrgList/OrgList.test.tsx, src/screens/OrgList/OrgList.tsx
bugfix
Fixes #1768 
Yes.
[Screencast from 2024-04-04 12-33-54.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/116624667/888ca95b-1989-4cf1-bf1a-f4cb9c6400ec)
Not Relevant.
**Summary**
This PR fixes the issue of organizations not being visible when one signs up as a `superadmin` other than the `defaultSuperadmin` or the `testSuperadmin`. Now, it works well with newly registered `LAST_RESORT_SUPERADMIN_EMAIL`.
No.
=> fix: Fixed organizations not visible

public/locales/en.json
Bugfix
Issue Number:
Fixes https://github.com/PalisadoesFoundation/talawa-admin/issues/1929
Already present
Summary
Field for translation was missing in en.json. Added that.
NO
Other information
Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes
=> fix: add english value for actionItemCompleted

src/screens/FundCampaignPledge/FundCampaignPledge.tsx
bugfix
Fixes #1977 
Yes 
https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/bb733acb-d90c-492c-bca7-4c28795ec17b
**Summary**
- Error was due to using userId (not present) in admin portal, fixed by using id (present)
- Refactored few lines of code 
No
Yes
=> Fixed error in pledge creation

.github/workflows/talawa_admin_md_mdx_format_adjuster.py
=> mdx file name changed

src/components/CollapsibleDropdown/CollapsibleDropdown.module.css, src/components/CollapsibleDropdown/CollapsibleDropdown.tsx, src/style/app.module.css
1. Reverting PalisadoesFoundation/talawa-admin#3463
1. Causing these errors on merging with the code base
1. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/13003284750/job/36265756676
=> Revert "Figma: Refactor CSS files in src/components/CollapsibleDropdown #3330"
